### PR TITLE
Scorched Girl 2 Electric Boogaloo

### PR DESCRIPTION
**Pull request by DaGoonCore**
## About The Pull Request
Miscommunication has happened an' am here to fix. +It happened again
~~Darn is it hard to make sharp lines and edges look good if there's a lot of them most of the time slicing through each one, the sprite is meant to look bit closer to how SG is presented in LoR.~~ Just fixing the basic issues with the sprite, replacing it with an updated model.

## Why It's Good For The Game

I didn't see the floating brown pixels or neither thought that the tiles on the floor would've masked SG's dark legs even further making her look like an ash mop therefore legs are now 1px longer and she's actually floating one pixel above the ground like Laetita.

## Changelog

:cl: DaGoonCore/GreedyCore
del: One frame in the angy SG sprite.
tweak: Replaced rest of SG sprites ~~making her overall brighter.~~ A functional front/back sprite. ~~Angry sprite eyes are now wandering.~~
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
I think it looks strange let me talk to our lead artist

**Comment by DaGoonCore** [comment]
More than fine. It's rather hard to find a good place between too Bright and too Dark when the floor color pallet is made with shades of Grey etc I'd say the first rendition almost flawlessly blends into its containment

**Comment by DaGoonCore** [comment]
Reminds me to local test my sprites.

**Comment by DaGoonCore** [comment]
Honestly I might've overcorrected, just lemme know if the first one looks good enough and just needs sprite fixing and I can just colorchange the fixed sprite to be more in-line

**Comment by DaGoonCore** [comment]
Ready for review, color palette changed to the old one as per insightful's directions.

**Review by dsmith328 — CHANGES_REQUESTED** [review]
Squash Commits, Rebase, and Fix DMI conflicts.

**Comment by DaGoonCore** [comment]
I'm getting lost in the sauce out here but atleast there's no conflicts???

**Review by DaGoonCore — COMMENTED** [review]
It's good now

**Comment by Kitsunemitsu** [comment]
Give it a squash and I'll merge

**Comment by dsmith328** [comment]
You have very much uh, messed up squashing the commits. And also didn't force push so the previous ones also exist. Would you like me to simply update the file myself and make a new pr to effectively speed merge or would you like to attempt to either salvage this one or make a new PR for it with just the one commit for the new sprites?

**Comment by DaGoonCore** [comment]
Guess this is what happens when a PR becomes stale, go on ahead. @dsmith328

**Pull request closed without merging**
