### PR TITLE
Sleeper and Chems Changes

### PR DESCRIPTION
**Pull request by PotatoTomahto**
## About The Pull Request
Sleepers
- Sleepers, operating console, cryo tubes now display sanity damage
- Sleepers display reagents of the occupant, code ported from Yogstation
- Removes code exclusive to Probital

EMAIS
- Adds the code to actually have a recharge time of chems, increased from 10 to 15 seconds
- Chem capacity reduced from 30 units -> 10 units

Chems
- Stamina damage dealt by Probital cut by third (10u > 35% fatigue, 20u > 76% fatigue)
- Probital healing reduced, OD threshold increased to that of salicylic acid
- Description changes of Salicylic Acid and Mental Stabilizer
- Fixes bug with Coagulant

## Why It's Good For The Game
Sleepers (and related medical machines) can now display the sanity and reagents of the occupant. Limiting chem generation of the EMAIS forces it to be a portable emergency injector compared to the sleeper. Nerfing stamina damage of Probital lets me remove my snowflake code in sleepers and make it more useful as a healing chem that's not great for combat.

## Changelog
:cl:
tweak: sleeper and chems
/:cl:

### CODE REVIEW

**Comment by civilCornball** [comment]
As a clerk main, I like taking a round every now and then to effectively be a healbot for the Agents. 
It’s bizarrely fun, tracking down low-Health agents and telling them off for letting themselves get that low.

After this PR, would this still be possible?

**Comment by Kitsunemitsu** [comment]
Not a big fan of the probital change because it stacks with sali and regens
As well as this, it encourages getting hopped up on drugs at the doc before a fight.
10u is safe.

**Comment by Kitsunemitsu** [comment]
That's.... the point??
Probital is unlimited.
Sali is limited. 

Probital heals you but requires you to take a moment before going back into combat
Sali is for mid combat

**Comment by Kitsunemitsu** [comment]
Issuing a DNM until I can figure out my thoughts on it.
I don't really want to give them another extremely powerful healing chem.

**Review by Kitsunemitsu — CHANGES_REQUESTED** [review]
Not interested in merging any chem or sleeper changes.

**Comment by InsightfulParasite** [comment]
For probital issue my two suggestions were to make it mix with other chems into one chem to create a threat of overdosing through mixing (chaotic option) or less effective in small doses since due to its metabolism var being the default 0.2 the 10u probital healed 112.6 brute in exchange for 102.3 stamina.
Upping the metabolism rate to 0.5 makes the formula 
(10 units/0.5 metabolism) cycles times 2.25 healing equals 45 healing
Drastic reduction in healing but less cycles mean less stamina damage it can apply.
The math for stamina damage is a bit wacky since it varies on how much stam damage is in the system but vaguely with the new values of 1.1, 1, 0.9, and 0.8 the stamina damage should be around 
(10 units/0.2 metabolism) cycles times 1 Stam equals 50 Stamina loss from the original 102.3 loss.

**Comment by InsightfulParasite** [comment]
Oh i forgot to mention if you wanted to remove the stamina damage all together you could swap it for the effect of the chem right below it in the code.

**Review by Kitsunemitsu — APPROVED** [review]
Merging so I can overhaul our chem system from the ground up.
There's stuff I want from this, and the maint won't stop whining.

**Pull request merged**
