### PR TITLE
Adds execution bullets

### PR DESCRIPTION
**Pull request by Coxswain-Navigator**
## About The Pull Request
Pay attention! This pull request has been changed significantly since the original proposal.
Adds execution bullets to the manager console. The bullets cannot be purchased or used unless an admin enables them through the new Toggle  Execution Bullets verb. For about 99% of players, this means they will not be accessible no matter what.
Execution bullets completely destroy their target, leaving all items behind. This is not reversible. All bullets fired are logged, and are the manager killing players by all intents and purposes. Use them carefully!
Also adds execution bullets in the form of a smite for admins not playing manager.

## Why It's Good For The Game
Finally, the last bullet. People will stop asking about it and admins can dole them out like candy to our delinquent players.

## Changelog
:cl:
add: Added execution bullets
/:cl:

### CODE REVIEW

**Comment by LanceSmites328** [comment]
Do... do we really need ANOTHER way to get rid of bodies? People already feed everything to Well, kind of immediately shutting down any dead-body based abno.

**Comment by Coxswain-Navigator** [comment]
It lets the manager do it.

**Comment by LanceSmites328** [comment]
> It lets the manager do it.

that.... doesn't really address the issue of it's another way body-reliant abnos get screwed with little effort.

**Comment by Coxswain-Navigator** [comment]
> > It lets the manager do it.
> 
> that.... doesn't really address the issue of it's another way body-reliant abnos get screwed with little effort.
Remember that this still costs a LOB point. It's useful when people need it, but probably not worth buying most of the time.

**Review by Kitsunemitsu — DISMISSED** [review]
These should not be able to be used on Sephirah, for obvious lore reasons, and the Rep should either be immune or spawn a kill team if killed by bullets.

**Review by Kitsunemitsu — APPROVED** [review]
Generally looks good, 
Hope it doesn't get enabled every round, but that's not my job lmao

**Pull request merged**
