### PR TITLE
Abnormality abilities can now hit rhinos

### PR DESCRIPTION
**Pull request by Halonexus**
## About The Pull Request
Added rhino combat support to most rcorp mode abnormalities and some additional changes:
-censored: reduced object damage to a reasonable level, ranged ability can now hit rhinos.
-melting love: reduced object damage to a reasonable level, aoe attack can trigger on and hit rhinos.
-mountain: fixed a runtime when attacking mechas, slam and scream now deal proper amount of damages to mechas instead of 1.
-nothing there: hello and goodbye now deal proper amount of damage to mechas instead of 1.
-funeral: the coffin attack can now damage rhinos.
-headless ichthys: jump attack can now target rhinos, jump attack and beam can damage rhinos, beam is affected by directional armor.
-helper: dash can now hit rhinos and is affected by directional armor.
-wayward: applied dash fixes and the dash can now hurt rhinos and is affected by directional armor.
-apex predator: the jump attack actually works now and can hurt rhinos, now able to backstab rhinos if in any of the 3 tiles behind them, backstab will stack with directional armor weakness when done from directly behind.
-wolf: dash and howl can damage rhinos.
-swan: scream can damage rhinos.
~~-monk: dash can damage rhinos and affected by directional armor.~~
-judgement bird: since livinginrange got fixed the z check is redundant and now actually allows to hit through containers including rhino mechs.
-thunderbird: dash can now damage rhinos and is affected by directional armor, thunderbolts can target and hurt rhinos, reduced zombie object damage to a reasonable level.
-yin: pulse and beam now damage rhinos, pulse can now trigger when moving next to piloted rhinos, beam attack can now trigger when shot by rhinos.

## Why It's Good For The Game
Rhinos will actually be affected by game mechanics.
Makes orientation a bigger deal in combat for both sides.
Stops certain abnormalities from one shotting all the doors and comms array.

## Changelog
:cl:
tweak: Most abnormality abilities can actually hit rhinos
tweak: Rhino directional armor applies to certain abilities
fix: apex predator jump skill works properly now
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Will have to read this later.

**Comment by Kitsunemitsu** [comment]
Is this ready for 515?

**Comment by Halonexus** [comment]
should be good

**Review by Kitsunemitsu — COMMENTED** [review]
On multiple occasions, we tested this.
It was tested and the outcome was positive. 

Cheers!

**Pull request merged**
