### PR TITLE
Sleeper tweak, pistol buff [BETACORP HOTFIXES]

### PR DESCRIPTION
**Pull request by PotatoTomahto**
## About The Pull Request
Sleepers will now only be able to inject 10 units of probital into someone without probital already. It is still possible to get stamina crit if you return for more probital, but ODs are no longer possible. Soda and Tough pistols have their damage buffed. Removed extra plushies from Safety/Welfare for consistency and added water cooler in Beta training because Alpha has one.

Revamps Tcomms so that the manager's office on Centcom Z-level can actually communicate.

## Why It's Good For The Game
Probital ODs from sleepers are stupid, and there have been too many times where it has ruined me (and other players as well). Pistols do twice the damage of clerk guns so they can have some use as a sidearm or when dual-wielded. Water and plushies are cool.

Manager needs to talk.

## Changelog
:cl:
add: water cooler to training
del: plushies (it had to be done)
tweak: sleepers can no longer give probital ODs (stamina crit still possible)
:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
I don't think pistols need a buff tbh.

**Comment by EgorDinamit** [comment]
They are a ZAYIN weapon. They are not meant to be good.
If anything, they should be slightly better than round-start equipment and that's it.

**Comment by Kitsunemitsu** [comment]
Having pistols at 8 damage is not the worst, considering that often they are sometimes used lategame for people fighting big bird.
Match gun deals 50 on Direct hit and Beak does 6 at rapid fire.
Having 8 damage pistols is not the worst.

**Comment by EgorDinamit** [comment]
Fix conflicts and I'll get it merged.

**Pull request merged**
