### PR TITLE
LC13 gamemodes

### PR DESCRIPTION
**Pull request by monochromatism**
## About The Pull Request

Adds three game modes that allow players to select a subset of abnormalities they'd like to manage:

- Lobotomy Corporation Plus - The game as it currently exists. All abnormalities.
- Lobotomy Corporation Pure - Only abnormalities from the original Lobotomy Corporation game. Does not include abnormalities present in, but radically changed from, vanilla Lobotomy Corporation.
- Lobotomy Corporation Side Branch - All abnormalities derived from side material, e.g. the artbook, Wonderlab, Limbus Company, and our original creations.

A vote between them is performed at the end of each round, and will set the gamemode of the next round. __(Warning: It may be advisable to adjust the length of votes so this vote can be concluded before the server restarts rather than exactly as it does.)__

This PR also prevents maps from being removed from the map vote pool just because they've been played recently.

## Why It's Good For The Game

Gives players a bit more control over how they play the game, and creates a framework by which future abnormality-selection-altering gamemodes may be added.

## Changelog
:cl:
add: Added gamemodes
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Based PR

**Comment by monochromatism** [comment]
Egor strikes again

**Comment by monochromatism** [comment]
reopening.

**Comment by dsmith328** [comment]
The great merge-conflict PR.

**Review by Kitsunemitsu — APPROVED** [review]
Has been working for a long time.

**Review by Kitsunemitsu — APPROVED** [review]
Has been running for a while; can be used for later.

**Pull request merged**
