### PR TITLE
Drunkenness Heals SP

### PR DESCRIPTION
**Pull request by civilCornball**
## About The Pull Request

Adds code to cause humans to *slowly* regenerate SP when drunk.
(I wish I could've coded it better. Feels awful just slapping it into life.dm)

## Why It's Good For The Game

-Gives everyone a reason to interact with bartenders, in all modes.
-Fixes lack of cheap SP healing in LoR13.

## Changelog
:cl:
tweak: Humans now slowly regenerate SP when drunk.
/:cl:

### CODE REVIEW

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Being drunk should turn you insane instead, that's how it works irl, too.
Jokes aside - "fixing lack of *cheap* SP healing" is the exact reason this PR is denied.

**Comment by civilCornball** [comment]
> Jokes aside - "fixing lack of _cheap_ SP healing" is the exact reason this PR is denied.

???
Could you explain why it’s important that LoR players only heal SP from medipens?

**Comment by civilCornball** [comment]
edit: oh that’s what that button does

**Comment by Coxswain-Navigator** [comment]
> > Jokes aside - "fixing lack of _cheap_ SP healing" is the exact reason this PR is denied.
> 
> ??? Could you explain why it’s important that LoR players only heal SP from medipens?

This is not the solution to a problem in one side gamemode.

**Comment by civilCornball** [comment]
Alright, fair enough.
Felt it’d work as flavor without affecting the standard gameplay of LC13 very much, if at all.

It’s effectively the Brute healing we already have from food, but given a White mirror in drinks.

**Pull request closed without merging**
