### PR TITLE
bloodbath

### PR DESCRIPTION
**Pull request by arnociiroc**
## About The Pull Request
bloodbath
## Why It's Good For The Game
bloodbath sprites
## Changelog
:cl:
add: bloodbath
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Hey there, Can you please link the last PR if you don't want to write a description

**Comment by EgorDinamit** [comment]
The commits are screwed once again. If you don't mind, I can just make a fix myself.

**Comment by arnociiroc** [comment]
please do, i have no idea WHY they are so scuffed

**Comment by EgorDinamit** [comment]
#267

**Pull request closed without merging**
