### PR TITLE
Discord sprite change and various sprite fixes

### PR DESCRIPTION
**Pull request by TemperanceTempy**
## About The Pull Request

I swear i always get nervous if i messed something up anyways-

Fixes various sprite misalignments on Hearth, Fragments gift, and the Blahaj Gift, and changes Yin's EGO sprite. Also adds Yin's EGO Weapon In-hands that match with the new sprites.

## Why It's Good For The Game

sprites being a pixel or two off can be really bothersome, also yin has been without inhands for way too long

## Changelog
:cl:
add: Yin EGO Weapon In-hands
tweak: Changed Yin EGO gear and weapon sprites
fix: fixed sprite misalignments on Hearth, Fragment Gift, Blahaj Gift
/:cl:

### CODE REVIEW

**Comment by InsightfulParasite** [comment]
image
Is this the one that was changed?

**Comment by InsightfulParasite** [comment]
image

Yeah the above one is a improvement. Much more sharp.

**Comment by InsightfulParasite** [comment]
If you tested how they look in game then i can give easy approval.

**Comment by TemperanceTempy** [comment]
> If you tested how they look in game then i can give easy approval.

I tested them to check for alignment issues, and i think everything was aligned, so it SHOULD be good. I will say the EGO armor was also swapped if you want to check that as well.

**Comment by InsightfulParasite** [comment]
You got a extra discord sprite in icons/obj/clothing/ego_gear/abnormality/waw.dmi listed as 0,0 if you delete that then it should be a good approval. Ill ask with the other maintainers when its good to merge this though just to see if theres any conflicts.

**Comment by TemperanceTempy** [comment]
> You got a extra discord sprite in icons/obj/clothing/ego_gear/abnormality/waw.dmi listed as 0,0 if you delete that then it should be a good approval. Ill ask with the other maintainers when its good to merge this though just to see if theres any conflicts.

whoops, thats not supposed to be there, ill get it removed asap, though my fork is being unruly and trash to squash in someone else's commit/PR, once thats done it should be good to go

**Comment by TemperanceTempy** [comment]
oook that wasnt supposed to happen, for some reason it added the TGS dmapi update into the pull whyd it do that

**Pull request closed without merging**
