### PR TITLE
Fixes black swan having no correct observation choices

### PR DESCRIPTION
**Pull request by Gboster-0**
## About The Pull Request

Black swan 1 wrong letter, breaking it. So i just deleted it

## Why It's Good For The Game

Bug bad

## Changelog
:cl:
fix: Black swan's observation is now correctly made
/:cl:

### CODE REVIEW

**Review by Kitsunemitsu — DISMISSED** [review]
Approved.

**Comment by Coxswain-Navigator** [comment]
This PR does not actually fix the problem fully, look again.

**Review by Coxswain-Navigator — DISMISSED** [review]
This PR does not actually fix the problem fully, look again.

**Review by Kitsunemitsu — APPROVED** [review]
Approved again

**Pull request merged**
