### PR TITLE
fixes cherryblossom gift slot

### PR DESCRIPTION
**Pull request by BlueHNT**
## About The Pull Request
minor fix

## Why It's Good For The Game
it's a brooch, not a hat

## Changelog
:cl:
fix: fixed incorrect slot of brooch
/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
It's not a brooch.

**Comment by Coxswain-Navigator** [comment]
This isn't meant to go in the brooch slot. If you intend to simply move the gift to a place that seems more reasonable on the icon you're more than welcome to do so, but this PR is misguided in its current state. I'm not going to close this, but my opinion is that the gift is fine in its current state.

**Comment by BlueHNT** [comment]
> This isn't meant to go in the brooch slot. If you intend to simply move the gift to a place that seems more reasonable on the icon you're more than welcome to do so, but this PR is misguided in its current state. I'm not going to close this, but my opinion is that the gift is fine in its current state.

True, I was looking at it quickly and it was more hair clip if anything, thought it'd fit the brooch instead of head slot. But ultimately it's your choice.

**Comment by vampirebat74** [comment]
> > This isn't meant to go in the brooch slot. If you intend to simply move the gift to a place that seems more reasonable on the icon you're more than welcome to do so, but this PR is misguided in its current state. I'm not going to close this, but my opinion is that the gift is fine in its current state.
> 
> True, I was looking at it quickly and it was more hair clip if anything, thought it'd fit the brooch instead of head slot. But ultimately it's your choice.

Brooch slots are meant to be on the chest, like a badge. This PR is completely unnecessary

**Comment by BlueHNT** [comment]
> > > This isn't meant to go in the brooch slot. If you intend to simply move the gift to a place that seems more reasonable on the icon you're more than welcome to do so, but this PR is misguided in its current state. I'm not going to close this, but my opinion is that the gift is fine in its current state.
> > 
> > 
> > True, I was looking at it quickly and it was more hair clip if anything, thought it'd fit the brooch instead of head slot. But ultimately it's your choice.
> 
> Brooch slots are meant to be on the chest, like a badge. This PR is completely unnecessary

It was done quickly and without thought at a request.

**Comment by Coxswain-Navigator** [comment]
If you have no intention to fix perceived issues with cherry blossom, then you can go ahead and close this. I'm going to leave it up in case you have any brilliant ideas.

**Comment by BlueHNT** [comment]
> If you have no intention to fix perceived issues with cherry blossom, then you can go ahead and close this. I'm going to leave it up in case you have any brilliant ideas.

There's no more issues I'm aware of, so this goes to the gutter.

**Pull request closed without merging**
