### PR TITLE
Realization armor value rework

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Nerfs all realization armor values based off how good the ability is.

## Why It's Good For The Game
I really, really hate that it's mandatory to get realizations. Now they are, as best, as good as aleph.

## Changelog
:cl:
balance: rebalanced all realization armor.
/:cl:

### CODE REVIEW

**Review by EgorDinamit — DISMISSED** [review]
Basing it on "how good ability is" is very subjective.
Make all realized armors have specific defined amount of combined armor, same as every other EGO armor.

**Comment by Kitsunemitsu** [comment]
> Basing it on "how good ability is" is very subjective. Make all realized armors have specific defined amount of combined armor, same as every other EGO armor.

I'm Disregarding and dismissing this.
This works for other EGO, but not for realizations as the abilities vary WILDLY in their usefulness.
I'm balancing this similar to EGO weapons as balancing wildly different abilities is not possible.
As the ability gets "stronger", the defences decrease. Again, we already use a similar system for EGO weapons.

**Comment by Kitsunemitsu** [comment]
I meant specifically Realization armor, as a correction for my dismissal.

**Comment by EgorDinamit** [comment]
This is a very subjective method of balance, like I said.
If "some abilities are too strong" - you rebalance them, not everything BUT them.

**Comment by Kitsunemitsu** [comment]
I know, and I'm okay with this.
We already do this for EGO weapons. 
This is a small part of the game that I would like to balance in this way.
As a rule of thumb: AOEs and Buffs get reduced a little, Healing gets reduced a LOT.
Standardization is dumb when these abilities go from "Kill yourself" to "Heal literally everyone in the whole game"

**Comment by Coxswain-Navigator** [comment]
> I know, and I'm okay with this. We already do this for EGO weapons. This is a small part of the game that I would like to balance in this way. As a rule of thumb: AOEs and Buffs get reduced a little, Healing gets reduced a LOT. Standardization is dumb when these abilities go from "Kill yourself" to "Heal literally everyone in the whole game"

I think the takeaway here is moreso that abilities such as "Kill yourself" and "Heal literally everyone in the whole game" are not very good ideas in hindsight.

**Comment by Kitsunemitsu** [comment]
> I think the takeaway here is moreso that abilities such as "Kill yourself" and "Heal literally everyone in the whole game" are not very good ideas in hindsight.

The takeaway is that we either have to balance along this or stifle creativity.
Which I am VERY much okay with just nuking abilities in general and bringing them back to normal EGO gear, with 1-5 set abilities.

**Review by EgorDinamit — DISMISSED** [review]
1. The nerf is too big and simply puts a lot of realized EGO out of use, while making some even better by sheer armor values.
2. This is a bandaid solution at its best. A proper "fix" to the whole realization issue would be reworking all the aspects of it, including how you realize the EGO and their abilities.

**Comment by Kitsunemitsu** [comment]
I do want this to be TMed for a while.

**Comment by Kitsunemitsu** [comment]
> 1. The nerf is too big and simply puts a lot of realized EGO out of use, while making some even better by sheer armor values.
> 
>     2. This is a bandaid solution at its best. A proper "fix" to the whole realization issue would be reworking all the aspects of it, including how you realize the EGO and their abilities.

This is an initial solution to an important issue in the game RIGHT NOW.
I need it test merged.

**Comment by Litberries** [comment]
a good bunch of these realizations look below aleph level to me

**Comment by Kitsunemitsu** [comment]
> a good bunch of these realizations look below aleph level to me

This is intended. You are trading out defenses for abilities.

**Comment by CrabbytheCrab** [comment]
I know that you dont give a shit about my opinion but I'm going to put some feed back anyways 

1. fearless might be one of the best realizations due to it having 7 in all and still having aleph tier dare devil and the extra pale makes the parry better, 
2. grinder 52 white res and black should be switched due to grinder having 2 black and -2 white, 
3. our galaxy should be 3/5/7/4 
4. Valor should be 6/5/5/8 to fit the other oz armors, 
5. I feel that eyes of god honestly isn't powerful enough to have a stat total of 170(due to the slow down not being that noticeable most of the time and 10% damage is nice but laughter and head of god adding +0.5 black or pale which leads to more than 2 x on abnormalities that heavily resist black or pale it just not that good. I guess could be given black 7 or 8 and switch white with pale, Sure you know when shits breaches too but that's not that useful since the manager can tell you
6. realized yin and yang should be the inverse of each other, 
8. why the fuck is living nest red 5 and black 7 that doesn't make sense at all it would be like making fallen colors have black 4 and red 8 they should be switches 
9. give al coda 7/10/7/0 so that there's a reason why someone would use actually want to realize de capo out side of appearance 
10. fallen colors ability and passive makes it a bit too chaotic since you end up killing or flinging other people due to the black hole and push back aoe damage so maybe it could get a small buff to 210 or 220 total,
11.  shell should be 200 total since its ability is basically you know free healing sure 10 hp isn't a lot but in amber midnight its a free win and its just an upgrade over current mimicry since it has the same stats rather than a side grade so unless you're going to bring old mimicry back shell is just an upgrade

**Comment by Kitsunemitsu** [comment]
> I know that you dont give a shit about my opinion but I'm going to put some feed back anyways
You're right, I don't care what you think. You're part of the reason why we're having this problem in the first place.

**Comment by CrabbytheCrab** [comment]
still doesnt mean I can't tell you some stuff you did was stupid. Also im still capable of power grinding and winning even without realizing due to aleph+ armors still exists like flowering night distortion, and, paradise lost so um are you going to nerf those as well?

**Comment by Kitsunemitsu** [comment]
Don't merge this, I have an alternative.

**Review by Coxswain-Navigator — APPROVED** [review]
This fixed issues in some areas and created some in others. We're going to merge this for now and hopefully come up with a better solution in the future.

**Pull request merged**
