### PR TITLE
Experimental Global Weapon Changes PR

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
All spears get a flat DPS boost, but a slight immobilization on attack.

## Why It's Good For The Game
I don't really like spear kiting, so I'm using this as an excuse to make spears deal a fuckload of DPS, but require a bit of setup.
Kiting with spears should a lot harder now, but if you can get a good tank setup, you should be able to obliterate shit.

Also adds in a new Spearman playstyle.

## Changelog
:cl:
balance: Spears do a metric fuckload of damage but now give you a stun on attack.
/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
I played a round with the spear changes, and it was truly awful. I implore you to change it from its current state.

**Comment by Kitsunemitsu** [comment]
In short: I HEAVILY dislike how spears are in this game.

**Comment by Kitsunemitsu** [comment]
The feedback to this PR has been generally positive if you look at democracy zone.
They do actually like it this way. 

There's better visual feedback on it now; so it should be better.

**Comment by vampirebat74** [comment]
From gameplay, I've noticed that these kind of invalidate the kiting gameplay you'd normally expect from combat in this game, instead forcing you to rely on other players. It's bad enough that several E.G.O were already considered unfit for use as weapons.

**Comment by Kitsunemitsu** [comment]
> From TM rounds, I've noticed that these kind of invalidate the kiting gameplay you'd normally expect from combat in this game, instead forcing you to rely on other players. It's bad enough that several E.G.O were already considered unfit for use as weapons.

I recently did a democracy vote on it, players agreed to this change
The other option is to nerf them to being about the same DPS as guns to discourage their use, or removing reach and I don't want that.

**Review by Coxswain-Navigator — APPROVED** [review]
I will be tentatively giving this a merge. I still have issues with it, and I'm not totally convinced that all players like it. You keep bringing up a democracy vote, but notably that vote did not have the option to not change spears. Nonetheless, it is "A" solution to the problem that will continue to exist until this is merged. However, I will not be blocking anyone that proposes and codes a better solution, nor will I allow this PR to be an excuse to do so.

**Pull request merged**
