### PR TITLE
Optimizes most LC13 uses of Range to incorporate urange and livinginrange

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Fits all uses of our range procs to their more optimal range procs.

## Why It's Good For The Game
livinginrange is much more intensive than urange or range for distances lower than 15, and urange is better than range for above 8.

This just makes it so that we have much cleaner code, and is a rather small change.

## Changelog
:cl:
code: Made most LC13 things use what I think is the most efficient range proc
/:cl:

### CODE REVIEW

**Comment by InsightfulParasite** [comment]
If this is based on the amount of tiles checked shouldnt we have a unified proc that automates which it checks for?
like
if(tile_Range > 8)
return range(tile_Range)

**Comment by Kitsunemitsu** [comment]
> If this is based on the amount of tiles checked shouldnt we have a unified proc that automates which it checks for? like if(tile_Range > 8) return range(tile_Range)

I would agree, but it is slower than manually calling it, and these sometimes run many times a second.

**Comment by InsightfulParasite** [comment]
> > If this is based on the amount of tiles checked shouldnt we have a unified proc that automates which it checks for? like if(tile_Range > 8) return range(tile_Range)
> 
> I would agree, but it is slower than manually calling it, and these sometimes run many times a second.

Fair

**Comment by InsightfulParasite** [comment]
Checking Urange functionality locally because i havent seen the urange proc before.

**Review by InsightfulParasite — APPROVED** [review]
Tested locally with urange and it seems to work. Approved.

**Pull request merged**
