### PR TITLE
Ordeal armor

### PR DESCRIPTION
**Pull request by CrabbytheCrab**
## About The Pull Request
Adds 6 new armors after the 6 non white midnight ordeals. Currently they're obtainable by well only.

Amber: Endless feast. Having  5/7/8/4 

Green: Painful purpose. Having 8/7/4/5 being a stat line I guess

Crimson: Meaningless March. Having 8/7/5/4 which sort of  makes it like an aleph version of clowns armor

Violet: Delusionist's end. Has 4/6/8/6(it also has a unobtainable form that can switch between the 4 colored pillars and change resistances that way)

Indigo: Familial Strength. Currently 7/3/8/6

Pink: Wonderland. Has 5/4/7/8. Just sort of exists to complete the set.

## Why It's Good For The Game

Makes well a bit more neat with the stuff it can give.

## Changelog
:cl:
add: 6 new ordeal armors, elegant amber silk too I guess
tweak: tweaked a few silk descriptions to be consistent with each other
imageadd: added images for ordeal armors and midnight ordeal book.
/:cl:

### CODE REVIEW

**Comment by Litberries** [comment]
green armor weaker than grobhammer smh my head

**Comment by CrabbytheCrab** [comment]
its faster though

**Comment by Litberries** [comment]
ok how much faster

**Comment by CrabbytheCrab** [comment]
grobhammer  has 1 slow down green has 0,75

**Review by LanceSmites328 — DISMISSED** [review]

**Comment by Kitsunemitsu** [comment]
I'm willing to merge this, if it's well only.

**Review by Kitsunemitsu — APPROVED** [review]
Looks fine to me, well only, no serious issues. Ready to go.

**Pull request merged**
