### PR TITLE
R-Corp Abnormality Reworks/Additions (Part 1)

### PR DESCRIPTION
**Pull request by EnderMage99**
## About The Pull Request

This PR does a few things:
First, It adds 4 new abnormalities to R-Corp!
1. Laetitia, A Easy Team Support:
She can place down explosive traps which when stepped on explode! She can also detonate them at will.
Also, She can spawn in spiders which players can possess. (However, They are heavily nerfed in R-Corp)
2. Baba Yaga, A Hard Team Support:
If they stay under her, she can move around the map at high speeds and land to deal MASSIVE damage to R-Corp.
Also, She can spawn mobs whenever she lands. 
3. A Contract, Signed, A Easy Team Support:
They can give out contracts that buff their fellow abnormalities!
They are also able to move around the map like Baba Yaga but for a much shorter time.
4. So That No One Will Cry, A Easy Team Tank:
They can use their Counter at will to block massive amounts of damage for their team!

Also, This PR reworks "Red Blooded American" by giving them an ammo gimmick, allowing them to deal much more damage in bursts.

Next, This PR also adds login information for all easy team abnormalities, helping out new players in figuring out what they can do!

Finally, This PR makes it so all hostile mobs are unable to attack themselves and all abnormalities give a visible message when they are possessed by players.

(Also, Adds a Jukebox for R-Corp so they can have music during their meetings.) :)

## Why It's Good For The Game

* First, Adding more abnormalities to R-Corp is useful since it allows for more variety in how a game plays out!
* Reworking Red Blooded American is great since it makes him a little bit more strong and more interesting to play as.
* Adding login information for all easy team abnormalities is helpful for new players since they have nowhere to find out what their abilities do or their role in the team.
* Making all hostile mobs unable to attack themselves just makes combat with them a little bit less frustrating when you keep on hitting yourself.
* Lastly, Giving all abnormalities a visible message when they get possessed is just a small bit of QoL so you have a better idea of who is active on your team.

## Changelog
:cl:
add: added login information for all easy team abnormalities
tweak: tweaked laetitia, baba yaga, a contract, signed and so that no one will cry so they could work in R-Corp
tweak: hostile mobs can't attack themselves and abnormalities now give a message when they are possessed
balance: rebalanced red blooded american by giving them an ammo mechanic
fix: fixed a bug with ardor blossom moth, where flames don't appear on rocks
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Going to issue a DNM for balance reasons at the moment.

Rcorp already has a sub-20% win rate. Until smth changes mechanically or culturally I don't really feel comfortable turning this gamemode into "Abnos Crush Rcorp" more than it already is.

**Comment by EnderMage99** [comment]
> Going to issue a DNM for balance reasons at the moment.
> 
> Rcorp already has a sub-20% win rate. Until smth changes mechanically or culturally I don't really feel comfortable turning this gamemode into "Abnos Crush Rcorp" more than it already is.

Oh, I didn't know that they had such a low win rate... (I wish I had more statistics like that.) But I can start working on another PR which buffs R-Corp.

**Comment by Kitsunemitsu** [comment]
After testing this PR, the state of balance in RCA simply isn't there.
They just like, don't have the firepower yet to deal with so many strong threats.

Rcorp already had very low win rates; but the meta isn't in a place to buff all abnormalities as of yet.
If you wish to make smaller PRs, I will look at them individually.

This PR can be reopened in the future.

**Comment by EnderMage99** [comment]
> After testing this PR, the state of balance in RCA simply isn't there. They just like, don't have the firepower yet to deal with so many strong threats.
> 
> Rcorp already had very low win rates; but the meta isn't in a place to buff all abnormalities as of yet. If you wish to make smaller PRs, I will look at them individually.
> 
> This PR can be reopened in the future.

Well, I will work on splitting this PR into multiple small PRs.

**Pull request closed without merging**
