### PR TITLE
Adds the ordeals of brown and revamped gold ordeals

### PR DESCRIPTION
**Pull request by Coxswain-Navigator**
## About The Pull Request
Splits the gold ordeals into two new ordeals.

- Brown ordeals - various mobs with various damage types, weak but plentiful
- Gold ordeals - Split damage mobs (except for dawn), mobs that use teamwork

- [x] Gold Dawn
- [x] Gold Noon
- [x] Gold Dusk
- [x] Brown Dawn

## Why It's Good For The Game
Makes the gold ordeals a bit more consistant.

## Changelog
:cl:
add: Added brown ordeals
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Can we pick a name that's not.... brown? It just sounds wrong. Bronze, Brass and Copper are all available

**Comment by Coxswain-Navigator** [comment]
If green is an acceptable name, why isn't brown?

**Comment by Kitsunemitsu** [comment]
Just sounds bad?

**Comment by Coxswain-Navigator** [comment]
Well it's called brown because peccatulum are supposed to be vermin so I am going to need a reason beyond you not liking it. I think it's fine.

**Comment by Kitsunemitsu** [comment]
If I was demanding a change I'd request changes.
If I dislike something minor or want more info I make a comment.

Brown just has a pretty bad connotation especially with the Brown Stain joke in our community, wanted to make sure that you're ok with that possible confluence if people turn out to dislike these. Bronze or Brass fits within our current naming scheme and is not as likely to be made fun of.

**Comment by Coxswain-Navigator** [comment]
I accept the consequences of naming them brown.

**Review by Kitsunemitsu — APPROVED** [review]
Mostly just a gut and clean. 
Looks good to me

**Pull request merged**
