### PR TITLE
Carnival Shop Location

### PR DESCRIPTION
**Pull request by LancashireladOnGitHub**
Removes the "Medium West Spawner" in the nest and replaces it with the soon to be used Carnival location

## Why It's Good For The Game
Another person is developing the Carnival and requested a quick shop that they can use, so here it is.

## Changelog
:cl:
Removed the Medium Spawner West in the nest and replaced it with the "Carnival" shop which will inevitably be used to house the Carnival
/:cl:

### CODE REVIEW

**Comment by LancashireladOnGitHub** [comment]
Closing this due to not hearing back from the developer it was meant for and its just causing some confusion here and there.

**Comment by TravisAngeI** [comment]
https://github.com/vlggms/lobotomy-corp13/pull/1397 has opened

**Comment by EnderMage99** [comment]
Also by the way, Once the Carnival is added into the game I will need the access into the base be changed into ACCESS_CARGO and then I will need 3 sets of Carnival Robes in the crates.

**Comment by LanceSmites328** [comment]
RE-Opened because the other relevant PR is open. Let me know if you want to abandon this PR and we can move it to someone else I think.

**Comment by LancashireladOnGitHub** [comment]
Closing this due to merging with the main PR https://github.com/vlggms/lobotomy-corp13/pull/1411

**Pull request closed without merging**
