### PR TITLE
Grinder MK4 now gibs corpses automatically

### PR DESCRIPTION
**Pull request by Coxswain-Navigator**
image

## About The Pull Request
What it says on the tin

## Why It's Good For The Game
Its cool I guess

## Changelog
:cl:
tweak: grinder MK4 now gibs corpses automatically
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Will need a second opinion, this is not only Smile's gimmick but throws the balance of an already good weapon out of wack,.

**Comment by Coxswain-Navigator** [comment]
> Will need a second opinion, this is not only Smile's gimmick but throws the balance of an already good weapon out of wack,.

This is indeed true. It only affects truly dead corpses... but I can see it being an issue if an abnormality's mechanics rely on that.

**Comment by Kitsunemitsu** [comment]
And that's the big issue... This is actually an weapon buff because it affects MOSB, Sweepers, and much more.

**Comment by Coxswain-Navigator** [comment]
I can make it only work on alive targets, if its the last hit

**Comment by Kitsunemitsu** [comment]
Neither Maintainers have given this PR approval, closing.

**Pull request closed without merging**
