### PR TITLE
Revert "makes the minigun good"

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
Reverts vlggms/lobotomy-corp13#2257

This PR made the original version deal over 200 red damage.
it can be redone to bring it in line with like 60-70, keep in mind the 3 slowdown.

### CODE REVIEW

**Comment by Litberries** [comment]
I get reverting the minigun buff but can you keep the rambo one?

**Comment by Kitsunemitsu** [comment]
> I get reverting the minigun buff but can you keep the rambo one?

Revert is a one button press, which is why I did it this way. I'm busy playin video games

**Comment by Kitsunemitsu** [comment]
Issuing emergency revert.

Defer to #2260
For a redo of this PR.

**Review by InsightfulParasite — APPROVED** [review]
Here we go.

**Pull request merged**
