### PR TITLE
Edits EGO sounds and updates crimson claw

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

- Edits sounds for some EGO guns.
- Adds special attack to crimson claw, which you can see below.

## Why It's Good For The Game

- More variety of ***sounds***. I simply didn't like how almost every weapon is using same sound, so here's that.
- So, I was looking through LC sounds and remembered that red-riding hood mercenary has throwing attack. I decided to add something similar to it, because it adds some flavor to it(it's a WAW weapon, after all). To prevent it being death beam 2.0, its damage is reduced per each mob hit, so it can't be really used to clear 999 worms with ease. It also lacks IFF, so be careful.

https://user-images.githubusercontent.com/53223414/199995977-0550f2d5-0116-40b0-85a2-e8568bf3cd7d.mp4

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Could have notified me while I was working on #392 and I could have made it easier for TM.

**Comment by EgorDinamit** [comment]
> Could have notified me while I was working on #392 and I could have made it easier for TM.

We'll merge 392 first and then work from there.

**Comment by Kitsunemitsu** [comment]
Also, Keep in mind crimson claw is a small weapon, maybe tone the damage back to 80?

**Comment by EgorDinamit** [comment]
> Also, Keep in mind crimson claw is a small weapon, maybe tone the damage back to 80?

Damage is reduced on every hit, and initial is meant to be somewhere around normal melee at max justice.

**Comment by Kitsunemitsu** [comment]
Gotcha, should be good then.

**Pull request merged**
