### PR TITLE
EGO gifts fix, change to abnormality proc cases

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

- EGO gifts will be applied after all work effects are done.
- Changes most of abnormality procs from under_line to CamelCase.

## Why It's Good For The Game

- Some gifts might shove into the insta-kill territory by giving/removing some attributes. This should fix it.
- All procs should be written in CamelCase, that's how it is.

### CODE REVIEW

**Review by dsmith328 — DISMISSED** [review]
Looks good to me, probably gonna fuck with every other PR though.

**Comment by Cupax3** [comment]
Discarding the merge conflict, would it be possible to isolate the refactors into their own atomar PR?

**Review by monochromatism — APPROVED** [review]
Compiles fine locally and I can't find any mention of the old names of anything that was updated to CamelCase. Gift fix also seems functional.

**Review by dsmith328 — APPROVED** [review]
Errors fixed :)

**Pull request merged**
