### PR TITLE
Artist 1984

### PR DESCRIPTION
**Pull request by TheBronJameOffical**
## About The Pull Request
Artist quirk has been an issue in all of these side gamemodes, from painting yourself pitch black to soap slipping. This stops that. 
We live in a society.

## Why It's Good For The Game
Pull that shit again and we'll end up like tg sybil.

## Changelog
:cl:
balance: artist quirk no longer exists on R-corp, W-corp, or LoR13
/:cl:

### CODE REVIEW

**Comment by civilCornball** [comment]
Problem: How are we going to get Crowbars now?

**Comment by TheBronJameOffical** [comment]
> Problem: How are we going to get Crowbars now?

In the city there are crowbars in the fixer vendor.
In R and W-corp you shouldn't have crowbars anyways.

**Comment by Gboster-0** [comment]
a very good PR, coulda removed the quirk outright or nerfed the stuff inside but chose a much better route

**Comment by EgorDinamit** [comment]
This is outrageous, how are people supposed to do cool art now? Literally 1984.

**Review by Kitsunemitsu — CHANGES_REQUESTED** [review]
Just check if the gamemode is in a list

**Comment by Kitsunemitsu** [comment]
It's not on freeze, and I do want to merge this PR sometime.

**Review by Kitsunemitsu — APPROVED** [review]
Code looks good

**Comment by EgorDinamit** [comment]
Noooooooooooooooooooooooo

**Comment by TheBronJameOffical** [comment]
War is peace
Freedom is slavery
Ignorance is strength

**Pull request merged**
