### PR TITLE
Adds third w-corp enemy type

### PR DESCRIPTION
**Pull request by Litberries**
## About The Pull Request

adds a peccatulum enemy type for W-corp, also has a boss
## Why It's Good For The Game

more is good, also kirie asked me to
## Changelog
:cl:
add: Added peccatulum enemy type for wcorp

/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
You may want to make weaker subtypes. For example, wrath and lust are midnight tier.

**Comment by Litberries** [comment]
yeah thats why i wanted to spawn them in uhh smaller amounts

**Comment by Litberries** [comment]
> You may want to make weaker subtypes. For example, wrath and lust are midnight tier.

to be fair so are G-corp managers

**Comment by Kitsunemitsu** [comment]
> You may want to make weaker subtypes. For example, wrath and lust are midnight tier.

W-Corp can put out pretty serious numbers with charge burst, especially becuase there will be 5-10 of them.

**Review by Kitsunemitsu — APPROVED** [review]
Approving *for now*, we will run a test this weekend and see what happens.

**Pull request merged**
