### PR TITLE
Tileset PR

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
First part of an experimental tileset PR.

## Changelog
:cl:
imageadd: Swapped out our tileset.
/:cl:

### CODE REVIEW

**Review by EgorDinamit — DISMISSED** [review]
The new 3/4 walls are too distant from our previous walls.
Additionally, a lot of on-wall objects will have to be adjusted to not look out of place (i.e. buttons, containment panels, painting, signs).
Doors will most likely have to be updated as well.

**Comment by Kitsunemitsu** [comment]
Closing PR, no interest in working on it at the moment.

**Comment by Kitsunemitsu** [comment]
Reopening, going to make a community vote on this later.

**Comment by Kitsunemitsu** [comment]
So, here's what we're at.

Walls and windows are done.

To do in a future PR is Doors and more walls.
This PR got extremely positive feedback, as it is a visual change, we spoke to the discord.
Along with this, multiple maps have been made with this PR in mind.
It's ready to go.

**Comment by Kitsunemitsu** [comment]
Forgot to put proof:
image

Vote on the visual change:
https://discord.com/channels/982658747304378520/982658748524941327/1191113417755459705

**Review by LanceSmites328 — APPROVED** [review]

**Pull request merged**
