### PR TITLE
NO SKATEBOARDING, NO SCOOTERS, NO PARKING PAST 6PM

### PR DESCRIPTION
**Pull request by TheBronJameOffical**
## About The Pull Request
Annihilates the crafting recipe for Skateboards and Scooters as they only exist to be abused

## Why It's Good For The Game
1984

## Changelog
:cl:
del: Removed scooter/skateboard recipes
/:cl:

### CODE REVIEW

**Comment by Gboster-0** [comment]
please comment out the code instead of removing it, for gods sakes

**Review by Kitsunemitsu — APPROVED** [review]
Approved

**Comment by civilCornball** [comment]
Why though? Crafting a skateboard is a fun Clerk quest.
Figuring out where to get the crafting materials, especially.

**Comment by KingSuperBOB** [comment]
> Why though? Crafting a skateboard is a fun Clerk quest. Figuring out where to get the crafting materials, especially.

Because skateboards lets you completely ignore slowdown and knockback

**Comment by civilCornball** [comment]
> > Why though? Crafting a skateboard is a fun Clerk quest. Figuring out where to get the crafting materials, especially.
> 
> Because skateboards lets you completely ignore slowdown and knockback

That sounds like a bug that should be fixed, not a reason to remove a fun sidequest.

**Comment by Gboster-0** [comment]
> > > Why though? Crafting a skateboard is a fun Clerk quest. Figuring out where to get the crafting materials, especially.
> > 
> > 
> > Because skateboards lets you completely ignore slowdown and knockback
> 
> That sounds like a bug that should be fixed, not a reason to remove a fun sidequest.

thats not a bug? thats an intended ss13 feature
you get slowdown immunity for getting stunned by anything that walks into you / anything that you walk into

**Pull request merged**
