### PR TITLE
Puts EGO guns under the ego_weapon subtype, copying some gun code and changing a lot of code

### PR DESCRIPTION
**Pull request by Gboster-0**
## About The Pull Request

- Removes the `item/gun/ego_gun` subtype, instead we'll now use `item/ego_weapon/ranged`.
- Weapons now no longer hold bullets until they are firing them.
- Weapons now now make casings on-demand only instead of them being coded-in, if they are necessary (shotguns)
- Moves ego weapons, both ranged and melee into the ModularTegustation folder
- Removes the CleanUp() proc
- Adds istype helpers for ego weapons, both ranged and melee
- Fixes constant casing hard-deletes
- Fixes adoration DOT bullets assigning timers to qdeleted objects in certain cases, making 14 runtimes

Due to the projectiles/casings no longer being a physical object in the gun, they cannot now be var-edited.
Something to consider fixing/adding in the future

## Why It's Good For The Game

> Removes the `item/gun/ego_gun` subtype, instead we'll now use `item/ego_weapon/ranged`.
- This PR removes a lot of stuff from the `/gun` subtype we were using, so maybe it'll improve performance.
- Also it fixes the examine descriptions/EGO guns dry-firing whilst having bullets. As now they dont have them.

> Weapons now now make casings on-demand only instead of them being coded-in, if they are necessary (shotguns)
- This kinda ties into the issue where casings constantly hard-deleted, but whatever. Point is that we dont need to constantly make casings if a weapon only fires 1 pellet.
- This should improve performance quite a bit, along with allowing any projectile to have any amount of pellets (fun!!!)

> Removes the CleanUp() proc
- Its copying Destroy(), and like 2 EGO's were using it

> Adds istype helpers for ego weapons, both ranged and melee
- We had a lot of things checking for eighter a melee or ranged ego weapon, dis is good for organisation
- Also this prevents a clerk pistol from being recognized as an EGO weapon in checks btw

> Fixes constant hard-deletes
> Fixes adoration DOT bullets assigning timers to qdeleted objects in certain cases, making 14 runtimes
- Bug fixes gud :3

## Changelog
:cl:
fix: EGO guns will no longer click because of bullets randomly dissapearing, ever
tweak: EGO guns have been recoded a good bit, expect bugs
/:cl:

### CODE REVIEW

**Comment by Gboster-0** [comment]
Thanks github, i wanted to press enter there. Brb gotta add the rest of the PR's comments

**Comment by Kitsunemitsu** [comment]
We should really replace Modular tegu with LC13 folders sometime soon.
Not a recommended change, just a comment

**Comment by Gboster-0** [comment]
> We should really replace Modular tegu with LC13 folders sometime soon. Not a recommended change, just a comment

Yup, one day

**Review by Kitsunemitsu — APPROVED** [review]
We have been tested this for so long, I think that due to it being a code improvement, it's good to go.

**Pull request merged**
