### PR TITLE
Alphacorp 2

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Adds containment, and generally redoes alphacorp.
Betacorp is given two more containments.
Removed 9 EMAIS from alpha and 8 from beta

## Why It's Good For The Game
Alphacorp will transition to a dense and combat heavy map instead of being objectively worse than beta 

## Changelog
:cl:
tweak: alphacorp is redone
tweak: 2 more containment to betacorp
balance: there are now significantly less EMAIS
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
And why are you removing practically all the hyposprays?

**Comment by Kitsunemitsu** [comment]
They're infinite, portable healing, and people have been using them to cheese work damage.

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Squash commits and I'll get it merged.

**Comment by Kitsunemitsu** [comment]
Ready to go

**Pull request merged**
