### PR TITLE
Updates Yin EGO sprites and Fixes sprite misalignments V2

### PR DESCRIPTION
**Pull request by TemperanceTempy**
## About The Pull Request

This is the 2nd attempt as fork did some wacky shit and tried to include a TGS update that already happened. I'm bad at this.
Updates Yin's ego armor and weapon with new sprites, as well as giving the weapon in-hands
Also fixes several sprite alignments in fragments gift, blahaj gift, and hearths weapon in one of the hands.

## Why It's Good For The Game

Fixes are good for the game, and yin has a lack of in-hands for way too long.

## Changelog
:cl:
add: yin In-hands
tweak: tweaked yins ego and weapon sprites
fix: fixed sprite alignments in fragment gift, blahaj gift, and hearths weapon inhands
/:cl:

### CODE REVIEW

**Comment by TemperanceTempy** [comment]
had to add a second commit/update because for some reason the ego_gifts file didnt actually get sent in the inital commit

**Review by InsightfulParasite — APPROVED** [review]
Checked the sprites and they are a direct improvement. Approved!!!

**Comment by InsightfulParasite** [comment]
Oh wait before we merge can you squash your commits. I think to get rid of the first commit you just rebase and the other two you just drag onto eachother.

**Comment by InsightfulParasite** [comment]
I forgot to ask you to squash the commits but i think it does that when i merge it.

**Pull request merged**
