### PR TITLE
no more bong

### PR DESCRIPTION
**Pull request by Luxyboo**
no more

## About The Pull Request

too many bongs

## Why It's Good For The Game

lessening the bongbong population

## Changelog
:cl:
del: Removed bongs
:cl:

### CODE REVIEW

**Comment by killer7luis** [comment]
No bong bongs?

**Comment by EgorDinamit** [comment]
Don't just comment out the code if you need it gone.

**Comment by Luxyboo** [comment]
it was requested by the code maker to just comment it out

**Comment by EgorDinamit** [comment]
The code doesn't magically disappear forever, the history of changes is kept, so if we want to re-add it later on we can just look at this PR.
Now, squash commits.

**Pull request merged**
