### PR TITLE
Cinderella Ego Dump

### PR DESCRIPTION
**Pull request by ScarSkit**
## About The Pull Request

Adds an ego suit: Carriage

## Why It's Good For The Game

An ego dump for Cinderella's pumpkin Carriage

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
You should add the changes at the end, but aside from that this is good to go!
Great first pr

**Comment by ScarSkit** [comment]
ah Cox told me I did not need to add cl because the pr was too small

**Comment by Coxswain-Navigator** [comment]
She is right that it is a good practice to add cl generally, but this is also such an extremely minor addition that players don't really need to be notified of it. A player might get this armor in a week or so as a nice surprise.

**Review by Kitsunemitsu — APPROVED** [review]
Approved.

**Pull request merged**
