### PR TITLE
Moves some LC13 essential structures to their own files [DONE]

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
Sloppily moves two lc13 structures that shouldnt cause conflicts to their own folder in ModularTegustation. Created a lc13_computer folder for our various computers. I tried to keep this small to avoid conflicts and atomize changes. Ill likely do small movements of sprites from random files to our dmi's.

Testing hasnt shown and errors caused by this move.

## Why It's Good For The Game
Assists with keeping LC13 code in a more recognizable spot rather than scattered about. 

## Changelog
:cl:
refractor: move regenerator.dm &  _adventure_console folder into lc13_obj refractor: move into abnormality computer consoles into their own lc13_computer folder
/:cl:

### CODE REVIEW

**Comment by Gboster-0** [comment]
i like this PR, tho why not move the LC computers into ModularTegustation

**Comment by InsightfulParasite** [comment]
> i like this PR, tho why not move the LC computers into ModularTegustation

I wasnt sure if it was too much of a move for a small PR.
I can move LC computers to Tegu if need be.

**Comment by Kitsunemitsu** [comment]
> > i like this PR, tho why not move the LC computers into ModularTegustation
> 
> I wasnt sure if it was too much of a move for a small PR. I can move LC computers to Tegu if need be.

Go for it

**Comment by InsightfulParasite** [comment]
> > > i like this PR, tho why not move the LC computers into ModularTegustation
> > 
> > 
> > I wasnt sure if it was too much of a move for a small PR. I can move LC computers to Tegu if need be.
> 
> Go for it

dONE!

**Comment by InsightfulParasite** [comment]
https://github.com/vlggms/lobotomy-corp13/issues/1609

**Pull request merged**
