### PR TITLE
Adds Dimension Shredder Realization, because why not

### PR DESCRIPTION
**Pull request by scionalu**
## About The Pull Request

https://github.com/vlggms/lobotomy-corp13/assets/80381079/b43b1d9d-a884-4d56-8c68-3bd17fc759e2

Adds Dimension Ripper (9/5/7/5) from Dimension Shredder (4/0/3/0)
The ability takes hostile mobs in view and does 3 dash attacks to random targets for each mob
1 second prep before attacking for 80 damage each dash
DPS for 1 target is 150, increases with each target since no extra prep, but it will target randomly

## Why It's Good For The Game

https://github.com/vlggms/lobotomy-corp13/assets/80381079/0b54311d-9ddd-41e2-8407-9cbb689a081c

## Notes

The only things missing are the suit icon and worn icon, since I have nothing to base it off from
And I have 0 creativity on art stuff

## Changelog
:cl:
add: Added Dimension Shredder Realization
imageadd: added realized spell effect, placeholder realized suit icon, placeholder realized worn suit icon,
/:cl:

### CODE REVIEW

**Comment by vampirebat74** [comment]
Incredibly based

**Comment by TheBronJameOffical** [comment]
furioso forma de W-corp

**Comment by TaculoTaculo** [comment]
Absurd W

**Review by LanceSmites328 — COMMENTED** [review]
Main reason I'm fine with this at the moment is due to the unique state of vulnerability you're put in while doing this. There *is* a risk to this. LMK when you're sprited up

**Comment by scionalu** [comment]
I FUCKING HATE REBASING FOR ICONS, IT BREAKS EVERYTHING

**Pull request closed without merging**
