### PR TITLE
Betacorp Update

### PR DESCRIPTION
**Pull request by Doctor-Derp**
## About The Pull Request
Updates betacorp.
image
Adds trophy cases to CC and edits the Angela statue display.
image
Expands Extraction per Egor's request.
image
Welfare displays.
image
Info+Telecomms+Records modifications.

## Why It's Good For The Game
Map is better now.

## Changelog
:cl:
add: (Betacorp Map) Adds trophy cases to Central Command, Newscasters and bot waypoints to each department, Modifies RO's and EO's offices.
/:cl:

### CODE REVIEW

**Review by monochromatism — APPROVED** [review]
Changes all look good from here.

**Comment by dsmith328** [comment]
Why railings in Extraction instead of Windows and a Windoor?

**Review by Kitsunemitsu — CHANGES_REQUESTED** [review]
Revert changes to the records backroom. I told you not to do this multiple times. The backroom exists so new players don't stumble across skin prophecy and other game ruining tools.

**Comment by Kitsunemitsu** [comment]
Keep 

> Why railings in Extraction instead of Windows and a Windoor?

Railings are a little jank with throwing ego over the it, but with windows you need to specifically open the windoor to toss ego

**Comment by Doctor-Derp** [comment]
> Revert changes to the records backroom. I told you not to do this multiple times. The backroom exists so new players don't stumble across skin prophecy and other game ruining tools. It's a place for mappers to put all the tools in one place.

I wasn't never told about this, and there's very little space between info and extraction, is it really that big of an issue? I've been told Don't Touch Me takes 40 seconds to press, and new players can always go work on abnormalities and get instakilled. If you want, I can add windoors instead.

**Comment by Doctor-Derp** [comment]
> Why railings in Extraction instead of Windows and a Windoor?

It looks nice and you can still place stuff on the table, it's mostly anti-table-hopping but can easily be destroyed or wrenched out the way.

**Comment by Kitsunemitsu** [comment]
As per our last discussion on the matter, where we went over the exact same point, the line of sight break is very important. Keep it in it's own room back in records. If you need to make the hallway leading into welfare longer, so be it.

**Comment by Doctor-Derp** [comment]
image

**Review by Kitsunemitsu — APPROVED** [review]
If we need to make the room bigger as we get more tools, we shall.
This will do for now.

**Comment by EgorDinamit** [comment]
Squash commits.

**Review by EgorDinamit — APPROVED** [review]

**Pull request merged**
