### PR TITLE
eta corp

### PR DESCRIPTION
**Pull request by ScarSkit**
## About The Pull Request

Adds Eta corps from Skits

## Why It's Good For The Game

more maps is good

## Changelog
:cl:
add: Adds G corp into maps file
add: Adds G corp json file
/:cl:

### CODE REVIEW

**Review by Kitsunemitsu — COMMENTED** [review]
This is a map we've had test-merged for weeks. I will merge when we get the JSON

**Comment by Kitsunemitsu** [comment]
Gonna test merge this; can you get a squash in?

**Comment by ScarSkit** [comment]
what is a squash?

**Review by Kitsunemitsu — APPROVED** [review]
Approved, Good map.

**Pull request merged**
