### PR TITLE
[DNM]100% More lore accurate (Removes black people and Gender)

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
image

## Why It's Good For The Game
People keep asking me to be 100% more lore accurate.

I'm fucking sick of it.
I'm sick of these fucking jokers thinking that just because everything is extremely accurate makes it good.
Shut up. Shut the fuck up.
It's almost as if every single time we tried to be more lore accurate, it failed, and is not fun.

See - Rabbit test.
See - TSO taking every single one of your boxes

Literally shut the fuck up.
I hate these fucking people that don't know a thing about game design trying to tell me to just make everything 100% as it is in the game and lore accurate, when that would make a significantly worse game.

So you know what? I'm going to make a fucking point.
This PR is going up, everyone can read my schizo ramblings because some random fucking guy on the discord thinks it's a good idea.

Do Not Merge.

## Changelog
:cl:
del: Removed black people
del: Removed male and female
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
erm... ackshually it should be only "albino" that's available cus in the game it's pure white and caucasian in SS13 is not completely white unlike albino...

**Comment by EgorDinamit** [comment]
I mean, if we look into LoR, it's not like everyone is pure white. There's no reason to do it.

**Comment by InsightfulParasite** [comment]
I cant believe someone actually asked you to make everyone dark white. They must of been joking.

**Comment by Kitsunemitsu** [comment]
Egor, this is a joke PR.
I'm making fun of all the people that ask me to make everything 100% lore accurate

**Comment by randal-the-vandal** [comment]
I was just joking around I did not mean to hurt anybody by saying all agents/clerks must be white. So I feel kinda bad for driving somebody over the edge

**Pull request closed without merging**
