### PR TITLE
Improves EO console code by getting rid of single-letter variables, adds slow extraction smites, gives an option for admins to be EVIL and GIVE THE ENTIRE SERVER SLOW EXTRACTION

### PR DESCRIPTION
**Pull request by Gboster-0**
## About The Pull Request

I randomly felt "man, this would be a great admin-only punishment", so here we are

This PR replaces single-letter variables in the EO console with actual names (wow!)
also replaces that one non-spanned line, because it was just sitting there
Also also, removes some un-necessary indentation, its best to avoid it when you can for better code readability

More importantly, adds in an admin-only smite that makes a specific mob forced to extract eighter based on their job, or 30 seconds of standing near the console doing nothing more than talking
You can even apply it to the entire server by manually editing the console's variables, ya know, for some fun

a lot of code taken from https://github.com/vlggms/lobotomy-corp13/pull/1640 , credits to kirie for it

## Why It's Good For The Game

Single-letter variables suck, thats all

Also i felt like the previous PR was a waste to throw away, so i think this re-imagined version would fit better with upsetting literally no one due to it being an admin-only feature

## Changelog
:cl:
code: KILLED SINGLE LETTER VARIABLES IN THE EO CONSOLE CODE, CODE FOR THE CODE GOD!
admin: added a new slow extraction smite, go ham with messing around!
/:cl:

### CODE REVIEW

**Comment by LanceSmites328** [comment]
Capitalized variable names should be lowercased

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
This is disgusting and pointless.
For what purpose would you be adding a new mob-level variable just to shit on random people?

**Comment by Litberries** [comment]
> This is disgusting and pointless. For what purpose would you be adding a new mob-level variable just to shit on random people?

that's... almost every sprite egor

**Comment by Gboster-0** [comment]
> This is disgusting and pointless. For what purpose would you be adding a new mob-level variable just to shit on random people?

Shit on shitty people specifically, thats how smites work
Also its /mob due to being unable to put it on /living (the console wont allow for that)

**Comment by Gboster-0** [comment]
for now, im gonna focus on some other PR's for devs/QoL. Putting this on the backline.

**Pull request closed without merging**
