### PR TITLE
"Tegu Translate"

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Adds a very simple translation to the game's interface in some places(i.e. preferences and lobby).
Right now it only supports Russian, if we're not counting English, but it is extremely easy to add support for new languages later on.

## Why It's Good For The Game

We have several Russian playeres that might be more comfortable using the native language for the interface and other most important details of the game.

### CODE REVIEW

**Comment by EgorDinamit** [comment]
image
Those are realy words and sentences, but Github won't show them, I suppose?

**Comment by EgorDinamit** [comment]
https://user-images.githubusercontent.com/53223414/202250945-c0127368-fea1-49d4-bdf4-42a210e3302d.mp4

**Review by dsmith328 — APPROVED** [review]
Looks good, I don't see any text errors at this time

**Comment by EgorDinamit** [comment]
It still needs some updates.

**Comment by killer7luis** [comment]
Hey... thats pretty good!

**Comment by Cupax3** [comment]
i forgor:skull: that i was supposed to review this

The concept itself is a neat idea, implementation-wise it *works* but isn't, in my opinion, well implemented as there may be future issues with maintainability or expandability. No-vote for now/barring further discussion.

**Comment by EgorDinamit** [comment]
Optimization/Code improvement is planned; It works for now and doesn't translate too much things to be worried about at the moment.

**Review by dsmith328 — APPROVED** [review]
Accessibility settings, in MY LC13? More likely than you'd think.

**Pull request merged**
