### PR TITLE
Changes cherry blossom gift

### PR DESCRIPTION
**Pull request by BlueHNT**
## About The Pull Request
Simple PR changes a small brooch into kitsune ears. It fits with the abnormality and is definitely gonna be disliked by some, but loved by others.

## Why It's Good For The Game
I wish to see the cries of those, which do not want to be a Foxboy.

## Changelog
:cl:
tweak: tweaked cherry blossom gift
/:cl:

### CODE REVIEW

**Comment by vampirebat74** [comment]
Still occupies the brooch slot and is irrelevant to the abnormality.

**Comment by BlueHNT** [comment]
> Still occupies the brooch slot and is irrelevant to the abnormality.

It is quite relevant and it occupies the "hat" slot. Just like the old brooch did for some reason.

**Comment by Coxswain-Navigator** [comment]
Why are you doing this? It has a gift already.

**Comment by Coxswain-Navigator** [comment]
Perhaps you should simply fix its slot mistake - who knows who made that. There is quite literally no reason to replace it just to appease furries either.

**Comment by Coxswain-Navigator** [comment]
Low effort shitpost PR.

**Pull request closed without merging**
