### PR TITLE
Made Crew sensors show everyone regardless of the z-level

### PR DESCRIPTION
**Pull request by UnokiAs**
## About The Pull Request
Commented out the code to check for z-level so it show everyone regardless of the z-level. So Manager can use the crewmonitor again.
Why not delete it ?
For easier revert (In case we get multi-z not likely).

## Why It's Good For The Game
Fix manager crewmonitor.

## Changelog
:cl: Unoki
fix: Manager crewmonitor
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
This isn't a proper solution, as it will show rabbits and admins in thunderdome.
What we need is multi-z station with manager's office on one of them.

**Comment by UnokiAs** [comment]
> This isn't a proper solution, as it will show rabbits and admins in thunderdome. What we need is multi-z station with manager's office on one of them.

It's one of the solutions/temporary, That's why I commented out the code instead of deleting.
Made this PR because I assumed that multi-z level will never happen.

image

**Comment by Kitsunemitsu** [comment]
If it's just the manager's office, IDGAF
It's the RO and EO being moved that I don't like

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
You also uncommented nullspace check, fix it.

**Pull request merged**
