### PR TITLE
[DNM] Adds a NEW ABNORMALITY!

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Adds in 
The Thing That Kills You. 
It's a Zayin-class abnormality that has one of 10 effects.

## Why It's Good For The Game
Market Research has shown that lobotomy corp fans like cock and ball torture. This abnormality does exactly that!
image

This is what it looks like
image

These are all the conditions under which The Thing that Kills you kills you!

If you have a weapon in your belt slot
If you DON'T have a weapon in your belt slot
If you're bald
If you have hair
If you're NOT a clerk
If it's been more than 20 minutes
If it's been LESS than 20 minutes
If you don't do a randomly chosen work type (just a 1 in 4 chance)
If you don't have max health
Or it just kills you guaranteed

It picks one on spawn, and if you fail to meet the requirements, you gib.

## Changelog
:cl:
add: Added The Thing That Kills you
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
This is a Joke PR.

**Review by dsmith328 — CHANGES_REQUESTED** [review]
It needs Records, smh. Also Squash Commits

**Comment by DiaFRAME444** [comment]
speedmerge.

**Comment by NiftyRyanyan** [comment]
The most balanced abnormality.

**Pull request closed without merging**
