### PR TITLE
Adjustable EGO Example

### PR DESCRIPTION
**Pull request by dsmith328**
## About The Pull Request
Example of adjustable EGO Armor. This example shifts In the Name of Love and Hate into it's Nihil version. It's a new subtype which should be easily addible to any existing armor with 2 edits, adding the type and adding to the "alternative_styles" list.

## Why It's Good For The Game
It's a cool change that opens up opportunities in the future, which I also want to see used in Jester of Nihil.

image
image
image

### CODE REVIEW

**Comment by dsmith328** [comment]
DO NOT MERGE UNTIL QoH EGO CHANGE IS REVOKED, THIS IS AN EXAMPLE OF WHAT IT CAN DO.

**Comment by Coxswain-Navigator** [comment]
Code looks good, just need things that actually use it.

**Comment by Kitsunemitsu** [comment]
Still not 100% sure if I want to go down this road, people will start to ask for X and Y alternates.
I'll get back to you tho

**Comment by dsmith328** [comment]
> DO NOT MERGE UNTIL QoH EGO CHANGE IS REVOKED, THIS IS AN EXAMPLE OF WHAT IT CAN DO.

Revoked and should be good to go

**Review by EgorDinamit — APPROVED** [review]
This adds nothing on its own, though I feel like it'd be nice to have ever so slightly different variants of same EGO(maybe different colors?).

**Pull request merged**
