### PR TITLE
Delays Ordeal Minimum Times

### PR DESCRIPTION
**Pull request by tile4**
## About The Pull Request
Increases the minimum times of ordeals.

## Why It's Good For The Game
Rounds should be slower now even if you got a lot of people working

## Changelog
:cl:
balance: rebalanced something
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Saying nothing for the code. I will say this PR is greenlit by me to be tested.

**Comment by Gboster-0** [comment]
Please make the changelog actually readable, some people probably use it

**Comment by tile4** [comment]
> Please make the changelog actually readable, some people probably use it

I only just realized this post. What do I need to do to fix the changelog?

**Comment by Gboster-0** [comment]
> > Please make the changelog actually readable, some people probably use it
> 
> I only just realized this post, sorry. What do I need to do to fix the changelog?

your changelog is currently " balance: rebalanced something "
instead of that, you should give an accurate description of what the PR does **in player language**
so for example " balance: ordeals will now arrive later, from 10 minutes at dawn to 30 minutes at midnight "

**Comment by Kitsunemitsu** [comment]
PR looks good to me, pretty sure it's been tested for a while, and is good to go.

**Review by Kitsunemitsu — APPROVED** [review]

**Pull request merged**
