### PR TITLE
Disables EO and RO

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Sets EO and RO job slots to 0

## Why It's Good For The Game
Headcoder doesn't like 'em, weren't supposed to exist.
Clerks can do their jobs going forwards.
image
image
image

## Changelog
:cl:
del: Removed EO and RO.
/:cl:

### CODE REVIEW

**Comment by WolfInfinity** [comment]
the code changes only remove one of the two, no? or am I reading it wrong

**Comment by JackFrost2424** [comment]
> the code changes only remove one of the two, no? or am I reading it wrong

Egor dislikes both, Kirie said he's giving him a loaded gun and asking him to fire, so it's for both.

**Comment by Kitsunemitsu** [comment]
> the code changes only remove one of the two, no? or am I reading it wrong

All Officers are a subtype of Extraction so we don't have to copypaste

**Comment by civilCornball** [comment]
RO's ability to slow down Abnormality adding is invaluable as a manager. I've often found myself asking the RO if they could slow down a dangerous abno... and then realizing that we don't have a RO.

EO's only useful for preventing stupid purchases - like that 'random clerk' buying the weapon instead of the armor you need to deal with a more difficult weapon.

**Comment by Doctor-Derp** [comment]
Is this a joke?

**Comment by Ben10083** [comment]
eh RO is fine, EO I can understand but it is moreso as a person to prevent dumb PE purchases (think QM for cargo)

RO is a good role though, most clerks dont even do records but having someone who's job it is to track that stuff is good

**Comment by TemperanceTempy** [comment]
Kirie has enough and distorts, the PR.

**Comment by EgorDinamit** [comment]
Just because I joke about EO/RO(and clerks) being trash doesn't mean I want them gone.

**Pull request closed without merging**
