### PR TITLE
Adds Rats Simplemobs (but not dumb)

### PR DESCRIPTION
**Pull request by TaculoTaculo**
## About The Pull Request
Adds Rat simplemobs for future use by gamemodes, also adds a humanoid file for any future city human type enemies.

re-did the pr because last one i did an oopsie

## Why It's Good For The Game
Rats Rats Rats we are the rats
Enemies to fight and populate the backstreets. Gives it a more alive feel.

## Changelog
🆑
add: Added rat enemies, added lc13_humanoids file
imageadd: Adds sprites for the rats
/:cl:

### CODE REVIEW

**Review by Coxswain-Navigator — COMMENTED** [review]
Play a sound when it fails to fire. You could even give it a smaller chance to explode in their hands and remove their ability to fire.

**Comment by TaculoTaculo** [comment]
> Play a sound when it fails to fire. You could even give it a smaller chance to explode in their hands and remove their ability to fire.

did both changes, plus added the sounds to the actual zippy gun too since it didnt do one when jamming.

**Review by Kitsunemitsu — APPROVED** [review]
Approved.

**Review by Kitsunemitsu — APPROVED** [review]
Re-Approving.

**Pull request merged**
