### PR TITLE
Fix weapon issue in weapon smartfridge

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
I put istype(o, istype(o, /obj/item))
A amateur move by me. I fixed it.
Also added a variable for light mask replacement.

## Changelog
:cl:
fix: weapon smartfridge
tweak: smartfridge light mask
/:cl:

### CODE REVIEW

**Review by Kitsunemitsu — DISMISSED** [review]
Looks good to me

**Comment by InsightfulParasite** [comment]
I think i accidentally deleted this thinking it was merged. Whoops.

**Comment by InsightfulParasite** [comment]
There is also a icon issue so i may fix that while this isnt merged.

**Review by Kitsunemitsu — APPROVED** [review]
Looks good to me

**Pull request merged**
