### PR TITLE
Buffs the shit out of Iron maiden

### PR DESCRIPTION
**Pull request by CrabbytheCrab**
## About The Pull Request

Buffs iron maiden's  multihits to scale with justice, made cooling it down only lowers the ramp up by 10.

Also reworks how it hurts you. Instead of doing a % of max hp  that scales when you attack, it now does red damage that scales the same way. It also now gibs you if you manage to get into crit or die from over using it. It also generates pe while getting hurt

## Why It's Good For The Game

Iron maiden just didn't work in practice due to how its multihits not scaling with justice really harmed it actually not being bad. It generating pe is silly and memey so it keeps it as a semi meme weapon while actually being able to put okish dps while doing do.

## Changelog
:cl:
balance: Made Iron Maiden an actual weapon now
/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
How much of a buff is this? Remember that you can stack up some pretty high red defense with mimicry and knight of despair. What is the DPS?

**Comment by CrabbytheCrab** [comment]
with the multihits scaling with justice its 256.833 dps
without the multihits scaling with justice its 176.25 at 130 justice

**Comment by Kitsunemitsu** [comment]
Iron maiden DPS is REALLY good at max ramp.
It gets 100 DPS if you can max ramp it. 
at level 2 Ramp, you get 50 DPS (better than Waw) and then it goes 75 > 100.

It does not need a buff for an aleph weapon you get from a zayin, even if it does hurt you.

**Comment by CrabbytheCrab** [comment]
justice scaling only actually effects 25% of that 100 dps which leads to stuff like crimson claw being capable to out dps it while trying to maximized the final stage's dps

**Comment by CrabbytheCrab** [comment]
just want me to make a pr just to give those secondary hits justice scalling?

**Pull request closed without merging**
