### PR TITLE
Spray can on walls again!

### PR DESCRIPTION
**Pull request by chesse20**
## About The Pull Request

The spray can now works on all the indestructible walls used in most/all maps
image

## Why It's Good For The Game
Decorate your workstations or Employee Housing or put up some funny graffiti

## Changelog
:cl:
add: Spraypaint on indestructible walls
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Is there a way to clean this?

**Comment by LanceSmites328** [comment]
> Is there a way to clean this?

As with any graffiti it should be soap/sprayer

**Comment by Kitsunemitsu** [comment]
Classic

**Review by Kitsunemitsu — APPROVED** [review]
Looks good to me. Great first PR

**Comment by chesse20** [comment]
yeah soap works just tested to make sure

**Pull request merged**
