### PR TITLE
Allows players to flush disposals while inside them.

### PR DESCRIPTION
**Pull request by civilCornball**
## About The Pull Request
Comments out a check for players being inside a disposal bin, to allow the UI to be accessed while inside that bin.

(god why is git such CBT)

## Why It's Good For The Game
Makes K-909 CHUTES _way_ easier to traverse.

## Changelog
:cl:
add: Players can now flush disposals while inside the bin.
/:cl:

### CODE REVIEW

**Comment by civilCornball** [comment]
I...
How do I remove these other commits?

**Comment by civilCornball** [comment]
Bumping, ready for review.

**Comment by Coxswain-Navigator** [comment]
I thought we were actively trying to discourage using these through map design - and why make this easier in particular?

**Comment by Kitsunemitsu** [comment]
Discussion with devs ended with this PR being shot down for not being conducive to gameplay.

**Pull request closed without merging**
