### PR TITLE
Newer Sprites Addition (Plus a new alt Sprite for an Abnormality)

### PR DESCRIPTION
**Pull request by tile4**
## About The Pull Request
This PR does the following:
- Gives Queen of Hatred new sprites that also are sizes more accurate
- Gives Helper newer sprites, breach directionals, and death sprites
- Adds a new alternate skin for a certain abnormality, unique gift and all.
- Gives Will You Play a new sprite.
- Makes abnormalities with death sprites that are in the code but don't appear in game actually appear in game.
The Queen of Hatred, Helper and Alt Sprite were made by Thatredbastard and the new WYP sprite is made buy Yuraizz

## Why It's Good For The Game
More detailed and accurate flair, and it is nice to have rare alt skins for abnormalities.

## Changelog
:cl:
tweak: some image code stuff for the abnos that are involved in the PR
imageadd: Added new QoH, Helper, and joke abno sprites
/:cl:

### CODE REVIEW

**Comment by InsightfulParasite** [comment]
Has all this been tested and works?

**Comment by tile4** [comment]
> Has all this been tested and works?

I tested it what was different and it all worked. when I tested I saw some mistakes that I proceeded to fix also so there's that too.

**Comment by Kitsunemitsu** [comment]
I might have maintainers vote on it and then have para merge it.
This is pretty divisive among maints.

**Comment by Kitsunemitsu** [comment]
Going to call @InsightfulParasite about this PR. The maintainer team is extremely divided on this.

**Comment by InsightfulParasite** [comment]
Ill approve it. Might as well. The PR needs a rebase though.

**Comment by tile4** [comment]
> Ill approve it. Might as well. The PR needs a rebase though.

Okay, rebased the PR

**Comment by tile4** [comment]
Oops, accidently closed it for a sec but I fixed it

**Review by InsightfulParasite — APPROVED** [review]
I still have the sprites for old QoH if we ever want to change back. Approved.

**Pull request merged**
