### PR TITLE
Adds pinocchio plush

### PR DESCRIPTION
**Pull request by Litberries**
## About The Pull Request
Adds the pinocchio plushie

## Why It's Good For The Game
The more plushies the better

## Changelog
:cl:
add: Added pinocchio plushie

imageadd: added pinocchio plush sprite ig
 Also changes it so agent can get pinocchio plush also
/:cl:

### CODE REVIEW

**Comment by Litberries** [comment]
fuck i did something wrong

**Review by Gboster-0 — CHANGES_REQUESTED** [review]
the pinocchio icon state in plushies.dmi is un-named. Please name it properly

**Comment by Litberries** [comment]
fixed?

**Comment by Gboster-0** [comment]
> fixed?

Yep, that works. Its currently un-obtainable until its mapped in or otherwise given a way to get it. But that can be added later

**Comment by Litberries** [comment]
I guess I could TRY doing something with plushie lover?

**Review by Kitsunemitsu — APPROVED** [review]
Approved.

**Pull request merged**
