### PR TITLE
The bear armor EGO resprite

### PR DESCRIPTION
**Pull request by killer7luis**
## About The Pull Request

I re-sprited that ugly ass mfo bear armor EGO

## Why It's Good For The Game

Its prettier

## Changelog 
:cl:
add: Pretty looking teddy bear armor
del: Ugly looking teddy bear armor

:cl:

image

### CODE REVIEW

**Comment by killer7luis** [comment]
Im incredibly proud of myself for making this

**Comment by EgorDinamit** [comment]
image
What's up with that one?
Also, you forgot to change the item sprite.

**Comment by killer7luis** [comment]
Oh, dw i gotchu

**Comment by killer7luis** [comment]
YAY

**Pull request merged**
