### PR TITLE
Hello! this is a template for me to view PR's and write them before i finish them! please pay no mind to this

### PR DESCRIPTION
**Pull request by Gboster-0**
## About The Pull Request

This makes us fairly up-to-date with upstream TG emotes. Makes things a lot neater in-code and adds a buncha stuff.

<details>
<summary>Ported PR's changing the file "code/modules/mob/living/emote.dm"</summary>

- https://github.com/tgstation/tgstation/pull/79481
- https://github.com/tgstation/tgstation/pull/79367
- https://github.com/tgstation/tgstation/pull/79216
- https://github.com/tgstation/tgstation/pull/78711
- https://github.com/tgstation/tgstation/pull/78632
- https://github.com/tgstation/tgstation/pull/78175
- https://github.com/tgstation/tgstation/pull/77323
- https://github.com/tgstation/tgstation/pull/77210
- https://github.com/tgstation/tgstation/pull/76483
- https://github.com/tgstation/tgstation/pull/76548
- https://github.com/tgstation/tgstation/pull/75345
- https://github.com/tgstation/tgstation/pull/74036
- https://github.com/tgstation/tgstation/pull/74909
- https://github.com/tgstation/tgstation/pull/74219
- https://github.com/tgstation/tgstation/pull/74029
- https://github.com/tgstation/tgstation/pull/74032
- https://github.com/tgstation/tgstation/pull/73146
- https://github.com/tgstation/tgstation/pull/73326
- https://github.com/tgstation/tgstation/pull/72950
- https://github.com/tgstation/tgstation/pull/72290
- https://github.com/tgstation/tgstation/pull/71281
- https://github.com/tgstation/tgstation/pull/71263
- https://github.com/tgstation/tgstation/pull/71161
- https://github.com/tgstation/tgstation/pull/70334
- https://github.com/tgstation/tgstation/pull/69963
- https://github.com/tgstation/tgstation/pull/69492
- https://github.com/tgstation/tgstation/pull/69127
- https://github.com/tgstation/tgstation/pull/69007
- https://github.com/tgstation/tgstation/pull/68948
- https://github.com/tgstation/tgstation/pull/68870
- https://github.com/tgstation/tgstation/pull/66321
- https://github.com/tgstation/tgstation/pull/65169
- https://github.com/tgstation/tgstation/pull/64490
- https://github.com/tgstation/tgstation/pull/62985
- https://github.com/tgstation/tgstation/pull/62639
- https://github.com/tgstation/tgstation/pull/62515
- https://github.com/tgstation/tgstation/pull/62394
- https://github.com/tgstation/tgstation/pull/59981
- https://github.com/tgstation/tgstation/pull/59797
- https://github.com/tgstation/tgstation/pull/59680
- https://github.com/tgstation/tgstation/pull/59645
- https://github.com/tgstation/tgstation/pull/59585
- https://github.com/tgstation/tgstation/pull/59245
- https://github.com/tgstation/tgstation/pull/59479
- https://github.com/tgstation/tgstation/pull/59495
- https://github.com/tgstation/tgstation/pull/58419
- https://github.com/tgstation/tgstation/pull/58098
- https://github.com/tgstation/tgstation/pull/56732
- https://github.com/tgstation/tgstation/pull/56698

</details>

<details>
<summary>Ported PR's changing the file "code/datums/emotes.dm"</summary>

- https://github.com/tgstation/tgstation/pull/79367
- https://github.com/tgstation/tgstation/pull/78175
- https://github.com/tgstation/tgstation/pull/76946
- https://github.com/tgstation/tgstation/pull/76654
- https://github.com/tgstation/tgstation/pull/76607
- https://github.com/tgstation/tgstation/pull/76548
- https://github.com/tgstation/tgstation/pull/76455
- https://github.com/tgstation/tgstation/pull/74219
- https://github.com/tgstation/tgstation/pull/72950
- https://github.com/tgstation/tgstation/pull/72290
- https://github.com/tgstation/tgstation/pull/69963
- https://github.com/tgstation/tgstation/pull/68954
- https://github.com/tgstation/tgstation/pull/68948
- https://github.com/tgstation/tgstation/pull/63710
- https://github.com/tgstation/tgstation/pull/62226
- https://github.com/tgstation/tgstation/pull/62206
- https://github.com/tgstation/tgstation/pull/60772
- https://github.com/tgstation/tgstation/pull/60432
- https://github.com/tgstation/tgstation/pull/60266
- https://github.com/tgstation/tgstation/pull/59645
- https://github.com/tgstation/tgstation/pull/59245
- https://github.com/tgstation/tgstation/pull/59479
- https://github.com/tgstation/tgstation/pull/59495
- https://github.com/tgstation/tgstation/pull/58821
- https://github.com/tgstation/tgstation/pull/57114
- https://github.com/tgstation/tgstation/pull/56912

</details>

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Gboster-0** [comment]
DAMMIT THIS WAS MEANT TO GO ON MY OWN REPO AAAAAAA

**Comment by TheBronJameOffical** [comment]
layigh and poijnt

**Comment by Gboster-0** [comment]
To be fair, its dumb that when you click "open a pull request" on your own repo it automatically switches to the parent one if you have the "i want to contribute to the parent repository" setting on

**Comment by timothymtorres** [comment]
I finally noticed this just now, strange.

**Pull request closed without merging**
