### PR TITLE
Simple Smile always makes you drop your weapon

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## Why It's Good For The Game
Smile cat is like hardcore countered by just laying down. This removes that

## Changelog
:cl:
balance: Buff to Gone with a Simple Smile.
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
You can just make it drop the weapons instead of using stun.

**Comment by Kitsunemitsu** [comment]
It's 1/10th a second of stun.
It's also less lines of code.

**Comment by EgorDinamit** [comment]
You are using a hack: Calling a proc1 that calls proc2, instead of using proc2.
In the end, you are executing more code for less reasons.

**Review by monochromatism — DISMISSED** [review]
Looks good to me. Make the graytider tide harder.

**Review by EgorDinamit — APPROVED** [review]

**Pull request merged**
