### PR TITLE
Reworks Abnormality Queue into TGUI

### PR DESCRIPTION
**Pull request by Cupax3**
## About The Pull Request
This just makes the console a bit fancier.
<details>
<summary>The new console look</summary>

image
</details>

## Why It's Good For The Game
TGUI bad, but TGUI gameplay good

~~the specific text can be changed if it does not suit the... style~~

## Changelog
:cl:
add: The Abnormality Queue is now a TGUI console
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Amending commit to shut the linter up

**Comment by Cupax3** [comment]
^ same tbh

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
As funny as it is - might want to change text to something proper("Currently queued abnormality", "Available extraction options").
Text for queued abno's level isn't colored, would be nice to update that.
Why the "TM" after currently queued abno's name?

**Comment by Cupax3** [comment]
> Why the "TM" after currently queued abno's name?

it was funni

**Comment by Cupax3** [comment]
> Text for queued abno's level isn't colored, would be nice to update that.

The button colour changes to account for the threat colour, the current selected abno now has its threat descriptor coloured

**Review by EgorDinamit — APPROVED** [review]

**Pull request merged**
