### PR TITLE
Echo Office Gear

### PR DESCRIPTION
**Pull request by EnderMage99**
## About The Pull Request

This PR adds gear which is used by the Echo Office fixers.

[Memory Forger]:
Eria is a shield good at blocking BLACK damage and heals the user on block.
Iria is a glove that deals BLACK damage and does a little knockback. However, when it is used with Eria it deals more damage and does more knockback.

Plated Outer Cover is armor good at taking BLACK damage.

[Sanguine Flame]:
Sunstrike is a spear that deals RED damage and inflicts BURN on hit.

Frilled Maid Outfit/Faux Fur Coat is armor good at taking RED damage.

[???]:
Sodom/Gomorrah are daggers that deal WHITE damage, increase the target's WHITE vulnerability on hit, and gain attack speed when dual-wielded. 

Neon Maid Dress is armor good at taking WHITE damage.

[???]:
Reverie Under the Stars is all-around good armor (Especially PALE damage) but slows down the users.

Also, This PR makes it so the flame and metal fixers drop this gear on death.

## Why It's Good For The Game

This gear can be a special reward for defeating these Fixers and these weapons hold new weapon gimmicks for CoL/City Fixers.

## Changelog
:cl:
add: Added the new Echo Office weapons
tweak: tweaked the current fixers
/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
You should probably discuss naming schemes, balance, and implementation with a maintainer.

**Comment by Coxswain-Navigator** [comment]
So... are these supposed to be actual fixers or some sort of non-human entity? The weapons are city weapons, but they are described and look more like E.G.O...

**Comment by EnderMage99** [comment]
> So... are these supposed to be actual fixers or some sort of non-human entity? The weapons are city weapons, but they are described and look more like E.G.O...

They are fixers, just high-level ones with a few trips to the outskirts. Since the gear they use is connected to them (Not E.G.O), I wanted to describe how the fixers would remember them.

**Comment by Kitsunemitsu** [comment]
This is SPECIFICALLY based off the bosses in COL/CF.

**Review by Kitsunemitsu — APPROVED** [review]
Approved, this is loot for CF/COL minor bosses. Looks great to me.

**Pull request merged**
