### PR TITLE
adds piscine mermaid

### PR DESCRIPTION
**Pull request by Caldony**
## About The Pull Request
Adds piscine mermaid, 

> When the work result was bad or medium, the Qliphoth counter decreased. 

> When the work result was good, Piscine Mermaid offered a gift if no other version of that gift was present in the facility.    

> The employee that wore the gift received greatly increased work rates. but the Qliphoth counter would periodically decrease as long as the gift was worn.  

> When the work result was good and was done by an employee wearing the gift, the Qliphoth counter increased.  

> When the employee wearing the gift took it off, Piscine Mermaid breached immediately.  

> When Piscine mermaid breached containment, she slowly suffocated everyone she could see and destroyed the gift if one was present. 

> If someone wore the gift at the moment of her breach, she would teleport to them and greatly reduce their speed, the gifted could not breath as long as Piscine Mermaid was alive.   <br>

> Piscine Mermaid took very little damage from anyone that wasn't the gifted, her resistances would come back to normal after the gifted's death.

the oxygen damage should be slow enough that it isn't that much of a threat unless you completely forget about it. unless you're the gifted in which case you're essentially on a drowning timer.

EGO ready
## Why It's Good For The Game

Mermaid is a another "gift" abnormality that unsurprisingly end up very needy and constant attention but gives great reward if you can deal with it.

## Changelog
:cl:
add: Piscine mermaid
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
You're currently missing records

**Comment by Kitsunemitsu** [comment]
You're currently missing records

**Comment by Caldony** [comment]
yeah I know I'll do them when it's no longer in draft mode

**Comment by Caldony** [comment]
records done, I also gave a shitty codersprite to her gift

**Comment by Caldony** [comment]
> Is she actually doing oxygen damage? That probably isn't a good idea.

the oxygen damage isn't half as fast as you'd think it is, and it's pretty obvious when you're being affected. I think it just makes fighting her slightly different from others and actually forces you to pay attention to something else than your main stats.

**Comment by Kitsunemitsu** [comment]
Fix conflicts and I'll manually test

**Comment by Caldony** [comment]
I've changed her gift lower qliphoth to 2.5 minutes instead of 5, the gift's work rates are already insane and I feel like she doesn't feel "needy" enough for the massive buff she already gives you. Especially since unlike rose people can just decide not to wear it

**Comment by Kitsunemitsu** [comment]
Oh great the Squash process didn't work.
You love to see it.

**Pull request merged**
