### PR TITLE
Twilight nerf

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Twilight is now nerfed from 9/9/9/9 to 8/6/8/8

## Why It's Good For The Game
Late game really feels like twilight makes it moot, because it's all round the best armor in the game.
This tones it back a little while still being in line with "being better than aleph"

## Changelog
:cl:
balance: twilight nerfed to 8/6/8/8
/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
Please touch nihil and false throne and ensure that they are held to the same standard.

**Comment by Coxswain-Navigator** [comment]
In addition, the comment no longer reflects the new total. Please update that.

**Comment by Kitsunemitsu** [comment]
False throne shouldn't be right now and Nihil is a different breed.

**Review by LanceSmites328 — APPROVED** [review]
Approved b/c it's fitting. It heavily resists the main birds damage types while being good all around.

**Pull request merged**
