### PR TITLE
Hp and sp bullets can no longer heal working agents

### PR DESCRIPTION
**Pull request by CrabbytheCrab**
## About The Pull Request

Prevents hp and sp bullets from healing agents that were working. This should be test merged only to test
## Why It's Good For The Game

Being able to use hp and sp bullets to heal working agents was a bug.
## Changelog
:cl:
fix: fixed hp and sp bullets being able to heal working agents
/:cl:

### CODE REVIEW

**Review by EgorDinamit — APPROVED** [review]
Code looks fine. Keep it test-merged for a while, let people get used to it.

**Comment by Kitsunemitsu** [comment]
I actually would like to take a deeper look with, and talk to the community has great issues about this and they brought up some excellent points I agree with. Issuing a DNM for now, TM is fine.

**Comment by Kitsunemitsu** [comment]
While I understand your concerns, I do not believe that removing this feature would be beneficial to the majority of the cast. It would only harm our gameplay loop in a few ways:

1. Bullets while working are a key point of emphasizing teamwork and communication. In fact, this is not only the main use of bullets, it is most of the key, immediate communication in the game.
2. New players, and medium skill players benefit far more from this as an emergency lifeline than high skill players do, due to them fucking up a little more than others.
3. Increases the reliance on luck. Without bullets while working, there is nothing stopping a horrible streak of luck from killing you outright.

I understand your concerns. However, I would like to issue a correction to this PR.
_Healing bullets should heal at half HP and SP while working._
This lets it be a lifeline, while also not being a go-to. Bullets are limited, so this should be a good compromise.

**Review by Kitsunemitsu — CHANGES_REQUESTED** [review]
Healing bullets should heal at half HP and SP while working, see my comment for more.

**Comment by Coxswain-Navigator** [comment]
I disagree with kirie and I am in favor of complete removal. The game worked fine before we added Hp and Sp bullets. Arguing that work damage is too punishing without them is just a bad faith argument that a handful of players are making.
Even if the healing is halved, the primary use is and will continue to be helping the top agent work constantly without breaks, which exacerbates some of the primary issues with game progress.
If our devs care enough about providing a safety net for players working on abnormalities, it should be added in a different form.

**Comment by Coxswain-Navigator** [comment]
> A possible compromise is to limit the number of bullets that can be applied to someone during a work. This allows managers to assist agents while curtailing the "just heal the top guy nonstop".

I considered this too, but consider that limiting it to 1 bullet is still limiting it to what is a full heal for a low level agent. This only has significant relevance when dealing with BLACK damage which makes it a rather poor solution.

**Comment by EgorDinamit** [comment]
Aside from benefiting the "power-grinders" and taking away every accountability for mistakes (picking wrong work types and working on low hp/sp), the healing bullets completely trivialize abnormalities such as CENSORED by taking away absolutely all of the threat they posess.
Bullets mid-work should not work at all.

**Comment by Kitsunemitsu** [comment]
> I disagree with kirie and I am in favor of complete removal of bullet use during work as opposed to halving the healing during work. The game worked fine before we added Hp and Sp bullets. Arguing that work damage is too punishing without them is just a bad faith argument that a handful of players are making. Even if the healing is halved, the primary use is and will continue to be helping the top agent work constantly without breaks, which exacerbates some of the primary issues with game progress. If our devs care enough about providing a safety net for players working on abnormalities, it should be added in a different form.

I will also mention; why would you make crabby make this PR to further ruin his reputation, instead of biting the bullet yourself?

**Comment by Kitsunemitsu** [comment]
> Aside from benefiting the "power-grinders" and taking away every accountability for mistakes (picking wrong work types and working on low hp/sp), the healing bullets completely trivialize abnormalities such as CENSORED by taking away absolutely all of the threat they posess. Bullets mid-work should not work at all.

We can also make healing during work a % based of remaining HP; the fact of it being an emergency measure is important. Why did you originally code it like this if it wasn't intended?

**Comment by EgorDinamit** [comment]
> We can also make healing during work a % based of remaining HP; the fact of it being an emergency measure is important. Why did you originally code it like this if it wasn't intended?

I didn't code bullets, I only coded a rework for manager console & added LOB upgrades. In the end, it was simply something that wasn't thought of, same as clerks healing agents mid-work.

**Comment by Kitsunemitsu** [comment]
Why is this even being argued the way community opinion is swaying when _you_ ALREADY have a shitty rep with them, this should be thoroughly given community feedback and concessions before we merge this PR.

Shield bullets are worse than HP/SP atm. Why should we remove the primary use of HP and SP bullets when we can instead nerf their use in this capacity and instead give shield bullets a better use? Why not let players purchase all colors of shield as a bundle instead; making them the better option for combat while nerfing the use of HP/SP bullets during working?

"X trivializes Y" is a dumb as fuck argument when it was trivialized for 1 years, 3 months and 21 days. That's a long time for maints to have an option to fix the 5-6 abnormalities it trivializes.

**Comment by Coxswain-Navigator** [comment]
Just because things were broken for a long time doesn't mean they shouldn't be fixed.

> 
> "X trivializes Y" is a dumb as fuck argument when it was trivialized for 1 years, 3 months and 21 days. That's a long time for maints to have an option to fix the 5-6 abnormalities it trivializes. Giving a garbage multiplier for the handful of abnos it trivializes is better than just removing one of the 2 things managers gets to do during non-combat anyways

**Comment by CrabbytheCrab** [comment]
> I didn't code bullets, I only coded a rework for manager console & added LOB upgrades. In the end, it was simply something that wasn't thought of, same as clerks healing agents mid-work.

Honestly is it weird that I feel like clerks healing agents mid-work is fine since it incentives them to help agents instead of doing fuck all

**Comment by Kitsunemitsu** [comment]
Okay!
I recently found a quirk with byond that manager bullets helps mitigate, and dying to it would be extremely unfair.

> if you're typing IC or OOC and you happen to hit enter to send your message right before the work finishes you will re-enter work on a random work type

This is unavoidable. but it is a bug we cannot fix to my knowledge, and manager bullet reloads now have to stretch 50% longer.
I do not want this to be a "Oops, I got scammed, and now will slowly die because POS has a 0 on insight)

If you want the specifics on exactly why it happens

> The work console has to refresh on every work to refresh understanding and more critical information like work rates
this shoves it to be the "in focus window". Hitting enter on this window, for some ungodly reason, starts another work and It's probably a quirk with the HTML code and byond

**Pull request closed without merging**
