### PR TITLE
changes animalism

### PR DESCRIPTION
**Pull request by CrabbytheCrab**
## About The Pull Request

Does some changes to animalism. Gibs on kill now, lowered the damage from 20 to 12 but now the hits after the first scale with justice,  checks if the target is next to you, and has hit text
## Why It's Good For The Game

Makes the secondary hits of animalism more like melee hits and the gibbing on kill makes it cooler.

## Changelog
:cl:
balance: rebalanced animalism's secondary hits to be more like melee hits and gibs on kill now
/:cl:

### CODE REVIEW

**Comment by CrabbytheCrab** [comment]
is there a problem with gibbing?

**Comment by LanceSmites328** [comment]
> is there a problem with gibbing?

Can be? I think that's something we need to set a precedent about with how we want it to work and if it should be treated as an 'execution' effect with some abnos or not

**Comment by TravisAngeI** [comment]
> is there a problem with gibbing?

Isn't this weapon dropped from one of the distortions in the CoL gamemode?
If I'm right, then gibbing is probably a bad idea as that is effectively a guaranteed permakill

**Comment by CrabbytheCrab** [comment]
Well no its apex predator's weapon

**Comment by vampirebat74** [comment]
> Well no its apex predator's weapon

It is re-used by the bunnyman

**Review by Coxswain-Navigator — APPROVED** [review]
Should be an improvement.

**Pull request merged**
