### PR TITLE
Oops, fixing up SG sprite

### PR DESCRIPTION
**Pull request by DaGoonCore**
## About The Pull Request
Miscommunication has happened an' am here to fix.
Darn is it hard to make sharp lines and edges look good if there's a lot of them most of the time slicing through each one, the sprite is meant to look bit closer to how SG is presented in LoR.
From:
oldsg
To:
wframes
waframes
oneframepdir

## Why It's Good For The Game

I didn't see the floating brown pixels or neither thought that the tiles on the floor would've masked SG's dark legs even further making her look like an ash mop therefore legs are now 1px longer and she's actually floating one pixel above the ground like Laetita.

## Changelog

:cl: DaGoonCore/GreedyCore
del: One frame in the angy SG sprite.
tweak: Replaced rest of SG sprites making her overall brighter. A functional front/back sprite. Angry sprite eyes are now wandering.
/:cl:

### CODE REVIEW

**Comment by DaGoonCore** [comment]
I really don't think she needs a south facing sprite but I'll make a patch job rn

**Comment by EgorDinamit** [comment]
Now it looks too bright and red eyes look goofy...

**Comment by DaGoonCore** [comment]
> Now it looks too bright and red eyes look goofy...

Well the eyes are like because her eyes move and dilate in her angry state but I can see them being too goofy/fast, will return to the darker colors too, It was a byproduct of lobmons wanting a more LoR accurate Scorched

**Comment by DaGoonCore** [comment]
It is going to look better in game but I should've gave the examples with the proper background huh?

**Comment by DaGoonCore** [comment]
nevermind shits broke

**Pull request closed without merging**
