### PR TITLE
Reworks F.A.N.

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
FAN's Success rate goes down by 3% for every successful work now.
FAN's PE was reduced from 18 to 12

## Why It's Good For The Game
FAN was too easy to work on, this PR fixes that.
Also decreases the insane FAN PE gain.

## Changelog
:cl:
balance: FAN has been reworked
/:cl:

### CODE REVIEW

**Comment by dsmith328** [comment]
> ## About The Pull Request
> 
> FAN's Success rate goes down by 2% for every successful work now. FAN's PE was reduced from 18 to 12
> ## Why It's Good For The Game
> 
> FAN was too easy to work on, this PR fixes that. Also decreases the insane FAN PE gain.
> ## Changelog
> 
> 🆑 balance: FAN has been reworked /🆑

Goes by 3% in code now.

**Review by dsmith328 — COMMENTED** [review]
This thing is really fucking funny honestly. Though doesn't this mean after 20 works it's chances are horrid? Maybe make it scale negatively faster but reset on Qliphoth meltdown?

**Comment by Kitsunemitsu** [comment]
It's based off good works. so it'll eventually get down to like 35 and people will get neutrals on it

**Review by dsmith328 — APPROVED** [review]
RIP the 100% success rate, but the gimmick should still hold up... ideally.

**Pull request merged**
