### PR TITLE
Fixes, qdel failure fixes and effect optimisations

### PR DESCRIPTION
**Pull request by Halonexus**
## About The Pull Request
Makes pretty much all abnormalities return hints on initialize and destroy, fixes qdel failures on abnormalities and wrath acid, optimises violet midnight, wn pulse, and white fixer; adds navbeacons to hurtinturf exclude.
Whitenight pulse doesnt cause lag spikes now, healing pulse is colored green as was originally intended supposedly, pulse range is extended.

## Why It's Good For The Game
Should reduce qdel issues and reduce tick drift on effect spamming mobs.

## Changelog
:cl:
fix: fixed wrath acid and abnormalities failing to qdel, white fixer cant act anymore during reflection if it starts mid attack, and can reflect punch damage now.
code: most abnos return stuff on initialize and destroy
/:cl:

### CODE REVIEW

**Review by EgorDinamit — DISMISSED** [review]
Frankly I have no idea what this reusable visual pool is, but let's give it a go.

**Comment by Halonexus** [comment]
> Frankly I have no idea what this reusable visual pool is, but let's give it a go.

The idea is to reuse effect objects instead creating and deleting thousands of identical objects. Its hard to measure the difference but in my testing after 20 minutes of sped up violet midnight tick drift was 40% lower.

**Review by EgorDinamit — DISMISSED** [review]

**Comment by Halonexus** [comment]
i will rebase this when somebody actually wants to merge it cause it gets conflicts from everything

**Comment by Kitsunemitsu** [comment]
I'm willing to re-approve.

**Comment by Kitsunemitsu** [comment]
Will read, working on some sprites

**Review by Kitsunemitsu — APPROVED** [review]
Reapproving. mostly a fix to initializations

**Review by Coxswain-Navigator — APPROVED** [review]
Kirie already approved, and after a cursory look, it looks fine to me.

**Pull request merged**
