### PR TITLE
Don't forget... the button incident

### PR DESCRIPTION
**Pull request by Gboster-0**
## About The Pull Request

Yoinks code from the following TG PR:
- https://github.com/tgstation/tgstation/pull/70099

In the process also turns it from an SM display to the shifts since someone harm-pressed the button successfully, since thats our round-end condition thats usually not desired

## Why It's Good For The Game

I think its a neat little detail, it does semi-conflict with the lore so i could kinda see how this PR could be denied. But i generally like persistance

## Changelog
:cl:
add: W-corporation has added new signs that show you how many shifts ago a "button" incident accured in a secure LC facility
/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
I like this a lot, remind me to give it a proper review later.

**Comment by Kitsunemitsu** [comment]
Heads up, I have to touch some minor mapping things soon. 
Not a problem, might juts have to rebase

**Comment by Gboster-0** [comment]
> Heads up, I have to touch some minor mapping things soon. Not a problem, might juts have to rebase

meh, its just 2 structure additions and ive got mapping hooks

**Review by Kitsunemitsu — APPROVED** [review]
Tested this on a live server, it's great. Congrats.

**Pull request merged**
