### PR TITLE
Red Buddy is Faster and deals more damage

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Red Buddy's move to delay decreased from 7 to 5. He's still slow but not fucking slow as shit
Red Buddy's Damage increased from 50-60 to 70-80

## Why It's Good For The Game
Red Buddy is an asshole on work, but he should be an asshole on breach as well.
He was intended to be slow and hit like a truck, but he's too slow and doesnt' hit hard enough

## Changelog
:cl:
balance: Red Buddy has been buffed to be faster and stronger
/:cl:

### CODE REVIEW

**Review by EgorDinamit — COMMENTED** [review]
Buddy now hits harder than Nothing There.
Not sure how I feel about it.

**Comment by Kitsunemitsu** [comment]
> Buddy now hits harder than Nothing There. Not sure how I feel about it.

Nothing there has ranged attacks and the Execute move.
Buddy is slow as balls and has almost no ranged option
I can tune it back a bit and just keep the speed.

**Comment by EgorDinamit** [comment]
Well, now it's a nerf...
Get minimum damage to at least 45.

**Comment by Kitsunemitsu** [comment]
> Well, now it's a nerf...
> Get minimum damage to at least 45.

He IS twice as fast now. I'll cut the players some slack

**Pull request merged**
