### PR TITLE
New Regenerator Visuals

### PR DESCRIPTION
**Pull request by InsightfulParasite**
Thank you DrDerp for Flower Regenerator Icon
Co-Authored-By: Doctor-Derp <40336142+Doctor-Derp@users.noreply.github.com>
## About The Pull Request
New Visual Icon and Visual effects for when the regenerator is buffed.
## Why It's Good For The Game
Allows players to see if a regenerator is buffed rather than having to check with a examine or use a Safety Kit on it. Also provides a funny 32x64 plant for each room.
image
image
Possible Separate Generator Sprite for General Generators
I really don't need to replace generator sprites since the smoke machine is fine but I just wanted it to have some LC flavor.
image

## Changelog
:cl:
add: Regenerator Visuals/Advanced Regenerator Gardening Visuals?
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Not sure how to feel about it being two tiles high, as it may obscure some things.

**Comment by Kitsunemitsu** [comment]
Actually that art pretty confined to safety and imo doesn't look good in other maps.
Maybe have both as an option?

**Comment by Kitsunemitsu** [comment]
Squash commits

**Comment by Kitsunemitsu** [comment]
Code looks good, merging.

**Pull request merged**
