### PR TITLE
Amber midnight

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Adds amber midnight and changes delays for other ordeals(white ones).

## Why It's Good For The Game

- New midnight.
- Fixes delays for white ordeals.

### CODE REVIEW

**Comment by InsightfulParasite** [comment]
Damn this was fast. Feels like yesterday I finished spriting the Worm.

**Comment by ReapedOni** [comment]
Now, I may not be a maintainer, but this thing is exclusively okay for high pop, as with low pop, the sheer quantity of fucking dawns that get thrown everywhere because of this fuck is a bit too absurd. I'd suggest dialing down either the dusk spawns by midnight or the dawn spawns by dusk. 
Source:
I had to kill 24 of them at a time at least 10 times the other day, excluding groups of lesser quantities.

**Comment by EgorDinamit** [comment]
Might be a good idea to scale spawns with the pop.

**Comment by dsmith328** [comment]
Only thought is the 20 second burrow cooldown might be a little short, considering this dude is real tanky

**Pull request merged**
