### PR TITLE
Adds new, Lobotomy Corp themed HP icon

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Adds LC themed HP icon, courtesy of GuardianZet
image

## Why It's Good For The Game
More Lobotomy Corp themed HUD icons

## Changelog
:cl:
imageadd: added new HP icon
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
I think the sprite is a little bit too big. It shouldn't be touching other UI elements.

**Comment by Kitsunemitsu** [comment]
can we shove the sanity icon up a couple pixels?

**Comment by Kitsunemitsu** [comment]
> I think the health sprite is just too big and makes it difficult to see the heartbeat line.

It changes color like the sanity icon

**Comment by EgorDinamit** [comment]
Potato does have a point. It is too big, to the point of seemingly being stretched in comparison to sanity icon.

**Pull request closed without merging**
