### PR TITLE
replaces mouth of god realized

### PR DESCRIPTION
**Pull request by RobotJanitor**
## About The Pull Request
Replaces the sprite for the "Mouth of God" Realization.

## Why It's Good For The Game
Replaces an old sprite as asked for.

## Changelog
:cl:
imageadd: Replaced "mouth" sprite.
/:cl:

### CODE REVIEW

**Review by Kitsunemitsu — CHANGES_REQUESTED** [review]
Can you move the old mouth of god to replace beak?

**Comment by RobotJanitor** [comment]
Shooould be done now. Old MoG should now be Beak.

**Review by EgorDinamit — COMMENTED** [review]
There's no need to replace normal beak with old realized sprite.

**Comment by Kitsunemitsu** [comment]
The old sprite was just beak but nicer. That's the problem.
We're also phasing out all those plate armor sprites.

**Review by Kitsunemitsu — APPROVED** [review]

**Pull request merged**
