### PR TITLE
Deltacorp - Branch D-317

### PR DESCRIPTION
**Pull request by Doctor-Derp**
## About The Pull Request
Implements a new high-medium population map, Delta Branch. Contains ~~25~~ 24 abnormality units, not including training rabbit. Every department implemented.

(Images may be outdated, view comments.)
## Asiyah Sector
Control Department:
image
Information Department:
image
Training Department:
image
Safety Department:
image
## Briah Sector
Central Command Department:
image
Welfare Department:
image
Disciplinary Department:
image
## Atziluth Sector
Records Department:
image
Extraction Department:
image

## Why It's Good For The Game
New map good.

## Changelog
:cl:
add: Adds Deltacorp, a high-med pop map.
/:cl:

### CODE REVIEW

**Review by Kitsunemitsu — APPROVED** [review]
image
Move these landmarks more to the ends of hallways as to make use of those spaces. Also add more at the red Xs. I feel like having more on the outskirts will force people into a choke with them, while also having them very close to the main rooms, in a "Hold this choke or die" situation.

Take these as a grain of salt, I approve.

**Comment by Doctor-Derp** [comment]
> Move these landmarks more to the ends of hallways as to make use of those spaces. Also add more at the red Xs. I feel like having more on the outskirts will force people into a choke with them, while also having them very close to the main rooms, in a "Hold this choke or die" situation.
> 
> Take these as a grain of salt, I approve.

Done. 👍

**Review by Kitsunemitsu — CHANGES_REQUESTED** [review]
Too many containments.
Keep containments to 24. you can cut 1 from welfare, discipline and training to keep it back to 24.
I don't want a repeat of people complaining about how other maps don't have as much containment as this one.

**Comment by Doctor-Derp** [comment]
> Too many containments. Keep containments to 24. you can cut 1 from welfare, discipline and training to keep it back to 24. I don't want a repeat of people complaining about how other maps don't have as much containment as this one.


Fixed, along with other bugs as well. Not has tidy as I would have liked, but it serves it's purpose and looks fine in-game.

**Review by Kitsunemitsu — APPROVED** [review]

**Comment by Kitsunemitsu** [comment]
Going to run one more test today and then merge

**Comment by Kitsunemitsu** [comment]
You heal in all hallways, that is an issue.

**Comment by Kitsunemitsu** [comment]
If the PAI were placed by you, remove. they are immune and have been tanking abnormalities

**Review by Kitsunemitsu — DISMISSED** [review]
If the PAI were placed by you, remove. they are immune and have been tanking abnormalities.
You heal in all hallways, that is an issue.

Also, put racks for the EO to toss shit on.
Please, PUT RACKS. It's not a problem on alpha because it's the lowpop map, but if you're above 20 players lots of EOs prefer to just toss shit outside.

**Comment by Doctor-Derp** [comment]
> If the PAI were placed by you, remove. they are immune and have been tanking abnormalities. You heal in all hallways, that is an issue.
> 
> Also, put racks for the EO to toss shit on. Please, PUT RACKS. It's not a problem on alpha because it's the lowpop map, but if you're above 20 players lots of EOs prefer to just toss shit outside.

No PAI on the map, but all of the other bugs have been fixed! I accidently used facility_hallway areas instead of the proper departmental areas. I finished it up, and added more rack parts to extraction.

**Pull request merged**
