### PR TITLE
Alriune

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Adds Alriune.

Slightly changed from how it was in LC, namely:
- Instead of 3 petals, it will only go up to 2.
- Qliphoth reduction on good result is only 50% chance.

## Why It's Good For The Game

New abnormality.

### CODE REVIEW

**Comment by EgorDinamit** [comment]
> What's the reason for changing it to 2 petals?

The sprite I have is facing south, so it simply looks better that way, in my opinion.

**Comment by Kitsunemitsu** [comment]
I have the EGO armor in #392, weapon will be incoming in a later PR.

**Comment by dsmith328** [comment]
Looks good except the merge conflicts. I can't see the files themselves in the checks sadly because the icon dif one didn't run.

**Review by dsmith328 — APPROVED** [review]
No issues seen so I'll be merging this.

**Pull request merged**
