### PR TITLE
makes the minigun good

### PR DESCRIPTION
**Pull request by Litberries**
## About The Pull Request

Makes the shrimp corp minigun actually good

## Why It's Good For The Game

The minigun is genuinely terrible currently and there is absolutely NO reason to use it, this just unnerfs the damage

## Changelog
:cl:

balance: rebalanced shrimpigun to remove it's damage nerfd

/:cl:

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
This item has no attribute requirements.

**Comment by Litberries** [comment]
> This item has no attribute requirements.

does now

**Comment by tile4** [comment]
> > This item has no attribute requirements.
> 
> does now

Issue I see with this is a main gimmick about S Corp weapons are that they should be usable by clerks. But it deserves to be stronger than the average soda gun thanks to its rarity and slowdown. I guess a good comparison could be the R corp minigun maybe?

**Comment by Litberries** [comment]
> > > This item has no attribute requirements.
> > 
> > 
> > does now
> 
> Issue I see with this is a main gimmick about S Corp weapons are that they should be usable by clerks. But it deserves to be stronger than the average soda gun thanks to its rarity and slowdown. I guess a good comparison could be the R corp minigun maybe?

issue is that the rcorp minigun is harder  to get than the soda minigun, so I'll just keep it with stat reqs

**Review by Coxswain-Navigator — APPROVED** [review]
Sure, why not.

**Comment by Kitsunemitsu** [comment]
Dude this is over 100DPS.... better than an aleph weapon

**Pull request merged**
