### PR TITLE
Rabbit Team Eye Color

### PR DESCRIPTION
**Pull request by Striketester**
I literally just made them the light blue that used to be only on the commanders helm.

### CODE REVIEW

**Comment by Striketester** [comment]
image

**Comment by Striketester** [comment]
image

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Squash commits, please.

**Comment by Striketester** [comment]
what should it be squashed with?

**Comment by EgorDinamit** [comment]
You should see how commits are squashed with git.
I'll try and squash-merge it now, but you should consider learning it.

**Pull request merged**
