### PR TITLE
The Armband PR

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Big Armband gameplay

## Why It's Good For The Game
Big Armband Gameplay.
I'm going to just put the armbands in the departments they belong to instead of as agent alt titles, gonna keep those to agent skill levels.

## Changelog
:cl:
add: Added departmental armbands
/:cl:

### CODE REVIEW

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
You should replace old armbands both in code and the maps.

**Comment by Kitsunemitsu** [comment]
Done

**Comment by EgorDinamit** [comment]
Conflicts...

**Comment by Kitsunemitsu** [comment]
I know. I'm having trouble with the tools.
I can't PULL Them from here but I can PUSH them to here
WHAT THE FUCK

**Pull request merged**
