### PR TITLE
Walls & Floors smoothing

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Smooths out textures.
We have a wall to use later, but I'm having trouble.
For now, we can use these

To Do in a future PR: Doors and walls.
image
image
image

Oh also makes generic soda machines SUCK MY ENEGY machines
image

## Why It's Good For The Game
I think a smoother look would really benefit us right now, to make us visually distinct.
Soon we can get cleaner but nicer walls and Airlocks.

## Changelog
:cl:
imageadd: swaps out textures for new ones
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
I think I already replied to similar PR before, those walls and floors look rather bleak and boring.
We had different wall sprites, didn't we?

**Comment by NiftyRyanyan** [comment]
I really don’t see how making the walls and floor bland would make it more visually distinct.

**Comment by Kitsunemitsu** [comment]
> I think I already replied to similar PR before, those walls and floors look rather bleak and boring. We had different wall sprites, didn't we?

We did, I had trouble getting them to smooth, can come in a future PR.
I just want a smoother look so our walls aren't so noisy.

**Comment by EgorDinamit** [comment]
Then let's wait for smoothed-out walls. These ones don't fit together.

**Comment by dsmith328** [comment]
Personally Im not a fan of the floors at the very least. That containment door kinda fucking SLICK tho

**Pull request closed without merging**
