### PR TITLE
Talking Bubbles

### PR DESCRIPTION
**Pull request by LanceSmites328**
## About The Pull Request
Readds talking bubbles. Does this SPECIFICALLY by porting over from Yogstation with minimal changes, like the removal of the "handle_typing_indicator" proc which was solely used to call INVOKE_ASYNC on another proc. Also adds a preference for if you want to see them or not, disabled by default.

## Why It's Good For The Game
It's VERY nice to see when people are talking.

### CODE REVIEW

**Comment by EgorDinamit** [comment]
I only have to say that this is done in a very weird way;
I'll give it a proper review at a later date.

**Review by EgorDinamit — COMMENTED** [review]
Looks good. Previous port had an issue where typing indicator would go away when clicking somewhere, among other things.
Leave it on test-merge, and if there's no new issues - merge.

**Comment by LanceSmites328** [comment]
Converting to Draft until I figure out how to fix the delay issue

**Comment by Kitsunemitsu** [comment]
We might have to report the old version for now, while it wasn't as good, it works really well/

**Pull request closed without merging**
