### PR TITLE
Warpco maps but maybe I dont squish it into someone elses PR this time

### PR DESCRIPTION
**Pull request by Moribox**
## About The Pull Request
adds 3 warpco rooms to the room pool, requested by Kirie

## Why It's Good For The Game
maybe it isnt.

## Changelog
:cl:
adds 3 warpco rooms.
/:cl:

### CODE REVIEW

**Comment by Moribox** [comment]
god DAMNIT.

**Comment by Moribox** [comment]
nothing I realized I can just manually get rid of the PRs that got attached that shouldnt have. This is fine, we are fine this is ok

**Comment by Kitsunemitsu** [comment]
What the fuck

**Comment by Moribox** [comment]
Im not entirely sure, but it only affects the files its supposed to so maybe its fine???

**Review by Kitsunemitsu — APPROVED** [review]
Wow this PR's commit history is fucked.
It looks fine to me however. It'll buff out.

**Pull request merged**
