### PR TITLE
Adds Visual to Immunity and Heal for Hostile Mobs

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
Requested by another dev. I cut down the healing effect a bit since i felt that 3 healing plus's were good enough.

image
Immunity. Kinda looks like a minecraft effect.
image
Healing, will be harder to see on green abnormalities like how immunity is hard to see on snow whites apple.

Testing shows it essentially works with no runtime errors... though i did lock a rabbit in a room with 3 abnormalities so that may not be a well controlled environment.

## Why It's Good For The Game
Will let players know they are doing negative or no damage. This MIGHT increase survival rate.

## Changelog
:cl:
add: Damage Effect proc
add: No_dam effect and sprite
tweak: Healing Sprite
/:cl:

### CODE REVIEW

**Review by Kitsunemitsu — COMMENTED** [review]
What's with all the randomly touched files?

**Comment by Coxswain-Navigator** [comment]
I don't see any problems with this. 👍🏽

**Comment by InsightfulParasite** [comment]
> What's with all the randomly touched files?

Hostile.dm was where i needed to make the damage effect proc for hostiles.
Effects.dmi was where i edited the original healing and added the no dam effect.
Miscellaneous.dm was where i edited the healing effect and made the no dam effects that appear on mobs.

**Review by Kitsunemitsu — APPROVED** [review]
Ready to go.

**Pull request merged**
